### ISSUE TITLE
Card form onFormComplete

### ISSUE THREAD

**Issue by Smart133594** [stripe/stripe-react-native#650] opened 2021-10-15 08:26 UTC
onFormComplete function in cardform, returns always emtpy card on android.

**Comment by mmdHussain** [comment] 2021-11-08 13:15
I'm having the same issue.After on complete card card-field gets clear out.

```
               <CardField
                      postalCodeEnabled={false}
                      placeholder={{
                        number: '4242 4242 4242 4242',
                      }}
                      cardStyle={{
                        backgroundColor: '#FFFFFF',
                        textColor: '#000000',
                      }}
                      style={{
                        width: '100%',
                        height: 50,
                        marginVertical: 30,
                        flexDirection: 'column',
                      }}
                      onCardChange={cardDetails => {
                        if (cardDetails.complete) {
                          console.log('OnCardComplete ::', cardDetails.complete);

                         setValidCard(true);
                          //setCard(cardDetails);
                         
                        }
                      }}
                      onFocus={focusedField => {
                        console.log('focusField', focusedField);
                      }}
```


https://user-images.githubusercontent.com/17882197/140748377-9a0b2b7b-a243-41c5-9450-a63a9700a140.mov

**Comment by charliecruzan-stripe** [comment] 2022-03-16 18:53
duplicate of https://github.com/stripe/stripe-react-native/issues/585

**Closed by charliecruzan-stripe** 2022-03-16 18:53 UTC
