### ISSUE TITLE
I can't hide PaymentSheet

### ISSUE THREAD

**Issue by losheredos** [stripe/stripe-react-native#892] opened 2022-04-18 11:17 UTC
**I want to hide the PaymentSheet or at least clear the information in it. I checked documentation few times but couldn't find any method for that. Do I miss something or there is no such feature?**

**Comment by charliecruzan-stripe** [comment] 2022-04-18 14:28
duplicate of https://github.com/stripe/stripe-react-native/issues/724

**Closed by charliecruzan-stripe** 2022-04-18 14:28 UTC
