### ISSUE TITLE
`createToken` return doesn't fit Typescript

### ISSUE THREAD

**Issue by JJK801** [stripe/stripe-react-native#408] opened 2021-07-09 06:59 UTC
**Describe the bug**
When using `createToken` method, `token` and `error` properties are wrapped in an extra `token` property

**To Reproduce**
```javascript
const {
  token: tokenData,
} = await createToken({ type: 'Card' })

// Stripe SDK seems not following the typscript architecture, this fix prevents it
const { token } = ((tokenData as unknown) as { token: Card.Token })
  ?.token
  ? ((tokenData as unknown) as { token: Card.Token })
  : { token: tokenData }
```
**Expected behavior**
this function should return as expected in typescript.

**Comment by thorsten-stripe** [comment] 2021-07-09 08:14
Duplicate of https://github.com/stripe/stripe-react-native/issues/344

The fix will roll out in the next release.

**Closed by thorsten-stripe** 2021-07-09 08:14 UTC
