### ISSUE TITLE
All place-holder doesn't show

### ISSUE THREAD

**Issue by aliMurtaja** [stripe/stripe-react-native#808] opened 2022-02-14 08:03 UTC
I used cardForm component in my app

the problem is that when i switch the app them from light mode to dark, All element will disappear.

is there any solution for that

**Comment by charliecruzan-stripe** [comment] 2022-03-16 16:32
duplicate of https://github.com/stripe/stripe-react-native/issues/771

**Closed by charliecruzan-stripe** 2022-03-16 16:32 UTC

**Comment by gauravag23** [comment] 2022-04-25 15:06
You can check color scheme and set cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}as per light or dark theme.

             <CardForm
                    cardStyle={{backgroundColor: Appearance.getColorScheme() == 'dark' ? '#000000':'#ffffff'}}
                 
                />
