### ISSUE TITLE
This merchant is having trouble accepting your payment right now by using different payment method OR_BIBED_07

### ISSUE THREAD

**Issue by Psutariya** [stripe/stripe-react-native#1435] opened 2023-06-27 09:48 UTC
**Describe the bug**
I use the google pay integration of stripe in react native but in android press the google pay button that time open the bottomsheet but after that some error show in production and working fine in development this error like this **this merchant is having trouble accepting your payment right now by using different payment method OR_BIBED_07**and I also change the add live key and testenv false but still same error in production.

To Reproduce
1.Click on 'Google Pay button'
2.Bottomsheet open after the press continue button

**Expected behavior**
open the paymentsheet and add the card successfully

**Desktop (please complete the following information):**
-OS:[ANDROID]
-Browser [chrome]

**Smartphone (please complete the following information):**
 -Device: [Android:oppo f9 pro]
 -OS: [10]
-Browser [estock browseri]
-Version [10]

![WhatsApp Image 2023-06-26 at 5 44 00 PM](https://github.com/stripe/stripe-react-native/assets/104578057/779d23ee-8189-459c-aa02-2c438706c5dc)

**Comment by seanzhang-stripe** [comment] 2023-06-28 10:43
Closing it as it's a duplicate of https://github.com/stripe/stripe-react-native/issues/1433

**Closed by seanzhang-stripe** 2023-06-28 10:43 UTC

**Comment by nicitaacom** [comment] 2024-07-29 09:03
I got same error with code 06
```
Something went wrong
This merchant is having trouble accepting your payment right now. Try using a different payment method. [OR_BIBED_06] OR_BIBED_06
```

I use stripe for payment with card
How to use google pay button without stipe?
Is it possible?
Docs "going live" on stripe don't helped me

mvp - https://codesandbox.io/p/devbox/google-pay-z25dg8

**Comment by anwargul0x** [comment] 2024-09-23 09:57
+1 Definitely a issue

**Comment by nicitaacom** [comment] 2024-09-26 08:16
Just use stripe - you get less errors
