### ISSUE TITLE
Immediately saving card when  adding thru presentPaymentSheet

### ISSUE THREAD

**Issue by m-elgamal** [stripe/stripe-react-native#597] opened 2021-09-18 05:48 UTC
On the checkout page, after the following promises:
await fetchpaymentsheetparams()
await initPaymentSheet()

once the promises resolves, customer has an option to choose payment option where they can enter a new payment method e.g. 4242 4242 4242 4242

If the customer leaves the checkout page back to the cart to add or remove and item, there's no way to attach this payment method to the payment intent even though i am reusing the same payment intent id when the page reloads with the updated cart accounting

**Describe the solution you'd like**
presentPaymentSheet to attach a new payment method to the related customer,
also would be nice to use the same presentPaymentSheet for customer payment method CRUD

**Comment by arekkubaczkowski** [comment] 2021-10-04 06:35
@m-elgamal payment methods are attached into the customer object instead of paymentIntent, so you need to make sure that you provide the same `customerId` in `initPaymentSheet` method. This scenario can be properly reproduced in our example app, see `PaymentsUICompleteScreen.tsx`

**Comment by m-elgamal** [comment] 2021-11-24 17:17
> @m-elgamal payment methods are attached into the customer object instead of paymentIntent, so you need to make sure that you provide the same `customerId` in `initPaymentSheet` method. This scenario can be properly reproduced in our example app, see `PaymentsUICompleteScreen.tsx` https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/PaymentsUICompleteScreen.tsx

So I revisited this issue again, seems there's some confusion about how the stripe payment sheet is currently designed
So, when the customer selects the payment methods like below
![image](https://user-images.githubusercontent.com/46498460/143284462-6ce0da7f-efda-44a5-a4d4-62aec3512579.png)
and enteres a credit card and selects save this card
![image](https://user-images.githubusercontent.com/46498460/143284498-56a6048d-4f4d-4386-9bd7-d059303b1f42.png)

and goes away from the checkout page then comes back to it that card is gone even though the the page is using the same payment intent and the same customer (both retrieved from the backend which retrieved them from stripe api for the second visit)
![image](https://user-images.githubusercontent.com/46498460/143284624-8e71cf84-fb81-4b09-a696-427bbf97552d.png) 

when i checked the dashbaord, the customer is created, but there's no cards attached to  it
![image](https://user-images.githubusercontent.com/46498460/143285109-b36e5d49-ec4d-4956-b19f-76b197bce994.png)

![image](https://user-images.githubusercontent.com/46498460/143285130-7630c2d3-de0c-484d-bd59-bd3926f451ed.png)

**Comment by SrBrahma** [comment] 2022-01-09 01:36
Any updates?

**Comment by Bamorem** [comment] 2022-01-20 15:48
I have the same issue, even if I'm using the same customer id and then I finalise the payment . all good except that the payment method is never saved to the customer

**Comment by charliecruzan-stripe** [comment] 2022-06-02 18:04
The payment sheet currently doesn't save the card details until after the payment is finalized. If you're hoping to save payment info for a future payment, have you considered using `SetupIntents`? 

Otherwise, please let me know what the use case is for this :)

**Comment by charliecruzan-stripe** [comment] 2022-08-12 23:03
Closing since we didn't get a response- if you'd like to save payment methods for later use, I suggest using Setup Intents- https://stripe.com/docs/payments/save-and-reuse

**Closed by charliecruzan-stripe** 2022-08-12 23:03 UTC
Labels: question
