### ISSUE TITLE
Unexpected error when running collectBankAccountForPayment

### ISSUE THREAD

**Issue by Seanmclem** [stripe/stripe-react-native#1096] opened 2022-08-22 21:15 UTC
**Describe the bug**
Following this [tutorial](https://stripe.com/docs/payments/ach-debit/accept-a-payment?platform=mobile&ui=react-native), to _Accept an ACH Direct Debit payment_. I've followed instructions to [get the payment intent](https://stripe.com/docs/payments/ach-debit/accept-a-payment?platform=mobile&ui=react-native#react-native-create-payment-intent) and return the client_secret, and returned that to the App.

Now, when I run `collectBankAccountForPayment` with all the appropriate inputs, I get 
```json
{"error": {
  "code": "Failed", 
  "declineCode": null, 
  "localizedMessage": "The operation couldn’t be completed. (STPPaymentHandlerErrorDomain error 2.)", 
  "message": "There was an unexpected error -- try again in a few seconds", 
  "stripeErrorCode": null, "type": null
} }
```

I'm using test-api-keys on BOTH the client and the server. The paymentIntent and client-secret seem valid. Then I run this, and get the error above

```javascript
        const { paymentIntent, error } = await collectBankAccountForPayment(
          client_secret,
          {
            paymentMethodType: "USBankAccount",
            paymentMethodData: {
              billingDetails: {
                name: `${userProfile.firstName} ${userProfile.lastName}`,
                email: userProfile.emailAddress,
              },
            },
          }
        );
```

Before upgrading Expo, running `collectBankAccountForPayment` would crash my project. Now it doesn't but still a vague and unhandled exception. What could I be missing? 

**Using:**
`"@stripe/stripe-react-native": "0.13.1",`
`"expo": "^46.0.0",` (but I've basically ejected with `expo run:ios`, could that be my issue? Expo is why I'm locked to `0.13.1`)
`"react": "18.0.0",`

Mac OS 12.5, M1 Pro
Simulator iPhone 13, iOS 15.5

**Comment by charliecruzan-stripe** [comment] 2022-08-22 21:40
If you're using `expo run:ios`, could you try this on a more recent version of `@stripe/stripe-react-native`? 

What does your server code look like (where you're creating the payment intent)?

**Comment by horozmc** [comment] 2022-08-22 21:44
Hi 
After 1 hour because 
Now business:)



iOS için myMail tarafından gönderildi


23 Ağustos 2022 Salı 00:40 +0300 kimden: ***@***.***  ***@***.***>:

**Comment by Seanmclem** [comment] 2022-08-23 00:01
> If you're using `expo run:ios`, could you try this on a more recent version of `@stripe/stripe-react-native`?
> 
> What does your server code look like (where you're creating the payment intent)?

Thanks for the quick reply! My server side code looks like this: 

```javascript
  const paymentIntent = await stripe.paymentIntents.create({
    amount: 5000,
    currency: "usd",
    setup_future_usage: "off_session",
    customer: stripeCustomerData.id,
    payment_method_types: ["us_bank_account"],
    payment_method_options: {
      us_bank_account: {
        financial_connections: { permissions: ["payment_method", "balances"] },
      },
    },
  });

  const { client_secret } = paymentIntent;

  return { client_secret };
```

It seems to return a valid paymentIntent.

And if I upgrade to the latest version of stripe-react-native, I get this error on `pod install`, seemingly due to a conflict with the "expo modules"

```
[!] CocoaPods could not find compatible versions for pod "Stripe":
  In snapshot (Podfile.lock):
    Stripe (= 22.4.0, ~> 22.4.0)
```

```
[!] CocoaPods could not find compatible versions for pod "StripeFinancialConnections":
  In snapshot (Podfile.lock):
    StripeFinancialConnections (= 22.4.0, ~> 22.4.0)
```

it does say `You should run 'pod update Stripe' to apply changes you've made.` but if I do that, it just throws the second error, with ` You should run 'pod update StripeFinancialConnections' to apply changes you've made.` and again and again.

Can I just skip or get rid of expo modules? OR is there a better way

**Comment by Seanmclem** [comment] 2022-08-23 01:34
Actually... It seems like it's working now. In both mentioned projects... With no real changes to either projects. Besides about another hour going by... I couldn't get it to work for days. Hmm
Even in the `"@stripe/stripe-react-native": "0.13.1",` project. I don't understand

**Comment by charliecruzan-stripe** [comment] 2022-08-23 16:29
> it does say You should run 'pod update Stripe' to apply changes you've made. but if I do that, it just throws the second error, with You should run 'pod update StripeFinancialConnections' to apply changes you've made. and again and again.

You need to run `pod update Stripe StripeFinancialConnections`.


> Actually... It seems like it's working now. In both mentioned projects... With no real changes to either projects. Besides about another hour going by... I couldn't get it to work for days. Hmm

I don't understand why this would happen either, but it looks like maybe it was a problem with some iOS dependency caching or something like that. Since it's working now, I'm going to close the issue, but if it comes back feel free to reopen and share how to reproduce the problem

**Closed by charliecruzan-stripe** 2022-08-23 16:29 UTC
Labels: question

**Comment by Seanmclem** [comment] 2022-08-24 12:37
@charliecruzan-stripe It was working for the past 2 days, including 2 minutes ago. Now, I am getting the same error again. I did nothing to fix or change dependencies between breakages... wait wait

It might be the email address I'm submitting with collectBankAccountForSetup. Seems like if it's not a valid email then it breaks it and throws the "try again in a few seconds" error. I also had dependency issues before but those are resolved

**Comment by charliecruzan-stripe** [comment] 2022-08-24 21:28
Gotchya, I'm in the process of making a fix for that right now. We'll bubble up the proper error.
