### ISSUE TITLE
[Android] Crash when adding a card with the UI sheet

### ISSUE THREAD

**Issue by tgensol** [stripe/stripe-react-native#223] opened 2021-05-14 15:44 UTC
When I tried to add a card, my app crash instantly

on Android 9.0

`Caused by: android.content.res.Resources$NotFoundException: File res/color/stripe_paymentsheet_elements_background_states.xml from drawable resource ID #0x7f0501fe`

`FATAL EXCEPTION: main
Process: com.appchoose.choose.android.debug, PID: 14291
android.view.InflateException: Binary XML file line #106: Binary XML file line #106: Error inflating class com.stripe.android.paymentsheet.ui.BillingAddressView
Caused by: android.view.InflateException: Binary XML file line #106: Error inflating class com.stripe.android.paymentsheet.ui.BillingAddressView
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:647)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)`

Do I have to configure something more on Android ? Or a ressource is missing ?

**Comment by thorsten-stripe** [comment] 2021-05-14 17:00
Duplicate of https://github.com/stripe/stripe-react-native/issues/212

**Closed by thorsten-stripe** 2021-05-14 17:00 UTC
