### ISSUE TITLE
In Android: the brand and last4  field in CardField  onCardChange callback wouldn't be set.

### ISSUE THREAD

**Issue by umer-viabletree** [stripe/stripe-react-native#1146] opened 2022-09-22 09:11 UTC
**Describe the bug**

"@stripe/stripe-react-native": "^0.19.0",
 "react-native": "0.64.2",
  on Android 
  compileSdkVersion = 33
  kotlinVersion = "1.7.10" 
  on Ios 
  xcode 14. and working fine.

**To Reproduce**
on CardField onCardChange callback getting this Object:
{
brand: null
complete: true
expiryMonth: 2
expiryYear: 42
last4: null
validCVC: "Valid"
validExpiryDate: "Valid"
validNumber: "Valid"
}

and on createToken method return error image below.
NOTE:  If I enter the same Test Card on Ios it works fine.

**Expected behavior**
If card valid it should be return brand and last4 as in Ios.

![1663837525603](https://user-images.githubusercontent.com/81979880/191707509-cc360552-e93d-41d0-a4ec-26f5aa3cef72.JPEG)

![1663837525603](https://user-images.github
<img width="562" alt="Screen Shot 2022-09-22 at 2 09 54 PM" src="https://user-images.githubusercontent.com/81979880/191707017-ab46c96e-d072-4ab9-b085-8d8a629c51ed.png">
usercontent.com/81979880/191706148-00040a26-4f7f-4d26-92d9-21156b3e8a55.JPEG)

 

@charliecruzan-stripe

**Comment by charliecruzan-stripe** [comment] 2022-09-22 15:17
Hi, please provide the code to reproduce. I tested this myself and am not seeing the same behavior

**Comment by SimonErlandsson** [comment] 2022-09-22 18:54
Having the same issue. Entering 4242 4242 4242 4242 04/24 242 while in test mode yields "Card details not complete". The exact same configuration worked previously.

**Comment by charliecruzan-stripe** [comment] 2022-09-22 18:55
Please provide a reproducible demo or code sample, otherwise it's very difficult to help. Tested this in [our example app](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/WebhookPaymentScreen.tsx) and it's working correctly.

**Comment by SimonErlandsson** [comment] 2022-09-22 19:09
`
<CardField
    onCardChange={e => console.log(e)}
    postalCodeEnabled={false}
    cardStyle={{
        backgroundColor: '#FFFFFF',
        textColor: '#000000',
    }}
    style={{
        width: '100%',
        height: 50,
        marginTop: 20,
        borderRadius: 5,
        borderWidth: 1
    }}
/>
`

Prints "{"brand": null, "complete": true, "expiryMonth": 2, "expiryYear": 42, "last4": null, "validCVC": "Valid", "validExpiryDate": "Valid", "validNumber": "Valid"}" when entering the card above.

**Comment by charliecruzan-stripe** [comment] 2022-09-22 19:10
Hm, that looks right so it seems like it's something with your project. Maybe you're using Expo and don't have the proper version installed?

**Comment by umer-viabletree** [comment] 2022-09-23 04:47
// @flow
import {
  CardField,
  StripeProvider,
  useStripe,
 
} from '@stripe/stripe-react-native';
import React, {useEffect, useMemo, useState} from 'react';
import {View} from 'react-native';
import {Actions} from 'react-native-router-flux';
import {connect, useDispatch} from 'react-redux';
import {addCreditCardRequest} from '../../../actions/CreditCardActions';
import {Button, CustomNavbar} from '../../../components';
import {strings, stripeKeys} from '../../../constants';
import {mixpanel} from '../../../helpers/mixpanelHelper';
import {AppStyles, Colors} from '../../../theme';
import util from '../../../util';
import styles from './styles';

const Stripe = props => {
  const {setIsNewPayment, isFromCart} = props || {};
  const [isValidInfoEntered, setIsValidInfoEntered] = useState(() => false);
  const [isSendingDataToServer, setIsSendingDataToServer] = useState(
    () => false,
  );

   const dispatch = useDispatch();
  const stripe = useStripe();

  async function onAddCardPressHandler() {
    setIsSendingDataToServer(true);
    await stripe
      .createToken({type: 'Card'})
      .then(tokenObj => {
        if (util.hasObjectWithKey(tokenObj, 'error')) {
          util.topAlertError(
            tokenObj?.error?.message ?? strings.SOMETHING_WENT_WRONG,
          );
     
          return;
        }

     
          }),
        );
      })
      .catch(error => {
        console.log({error});
        setIsSendingDataToServer(false);
        util.topAlertError(error);
      });
  }

  

  return (
    <>
    
      <View style={styles.stripeInputCont}>
        <StripeProvider
          publishableKey={stripeKeys.publishableKey}
          urlScheme="your-url-scheme"
          threeDSecureParams={{
            backgroundColor: Colors.background.primary, // iOS only
            timeout: 5,
            label: {
              headingTextColor: Colors.text.primary,
              headingFontSize: 13,
            },
            navigationBar: {
              headerText: '3d secure',
            },
            footer: {
              // iOS only
              backgroundColor: Colors.background.primary,
            },
            submitButton: {
              backgroundColor: Colors.background.purple,
              cornerRadius: 12,
              textColor: Colors.text.primary,
              textFontSize: 14,
            },
          }}>
          <CardField
            postalCodeEnabled={true}
            placeholder={{
              numberPlaceholder: 'Card Number',
            }}
            cardStyle={{
              backgroundColor: '#FFFFFF',
              textColor: '#000000',
            }}
            style={{
              width: '100%',
              height: 50,
              marginVertical: 30,
            }}
            onCardChange={cardDetails => {
              setIsValidInfoEntered(cardDetails?.complete ?? false);
            }}
            onFocus={focusedField => {}}
          />

          <Button
            color={Colors.text.white}
            onPress={onAddCardPressHandler}
            isLoading={isSendingDataToServer}
            disabled={!!!isValidInfoEntered || !!isSendingDataToServer}
            style={[styles.addToCardButton]}
            textStyle={styles.addCardText}>
            {strings.ADD_CARD}
          </Button>
        </StripeProvider>
      </View>
    </>
  );
};

Stripe.propTypes = {};
Stripe.defaultProps = {};

const mapStateToProps = ({}) => ({});
export default connect(mapStateToProps, null)(Stripe);

**Comment by umer-viabletree** [comment] 2022-09-23 04:50
when I do postalCodeEnabled={true} it work fine  with zip/postcode. 
and placeholder also not customize/set both ios and android.

**Comment by SimonErlandsson** [comment] 2022-09-23 13:22
Can confirm that setting postalCodeEnabled={true} solves the problem for me as well. I believe I have the latest version of the Stripe plugin installed. Any idea of the cause?

**Comment by charliecruzan-stripe** [comment] 2022-09-23 16:18
Hm even with `postalCodeEnabled={false}` it's working for me. Like I said above, the best thing to do would be to provide a link to a GH repo that I can use to reproduce, since our example app is working for me.

**Comment by umer-viabletree** [comment] 2022-09-24 08:49
> Can confirm that setting postalCodeEnabled={true} solves the problem for me as well. I believe I have the latest version of the Stripe plugin installed. Any idea of the cause?

I think I will work for you also. check it

**Comment by charliecruzan-stripe** [comment] 2022-10-10 17:48
Would like to help, but if a reproducible demo isn't provided then I'll close this issue as not actionable. The best thing to do would be to provide a link to a GH repo that I can use to reproduce, since our example app is working for me.

**Comment by umer-viabletree** [comment] 2022-10-11 15:55
> Would like to help, but if a reproducible demo isn't provided then I'll close this issue as not actionable. The best thing to do would be to provide a link to a GH repo that I can use to reproduce, since our example app is working for me.

okay. I will make a repo

**Comment by umerhayat54** [comment] 2022-10-21 05:23
same issue.

**Comment by charliecruzan-stripe** [comment] 2022-10-21 16:03
Closing this issue for now until a reproducible demo is provided. Sorry everyone, but without a way to reproduce this bug it's very hard to help. If you're having this issue, please share a link to a GH repo that I can clone in order to see the same behavior.

**Closed by charliecruzan-stripe** 2022-10-21 16:03 UTC
Labels: reproduce

**Comment by pavelglebov** [comment] 2022-11-27 15:52
Sad outcome. Looks like this issue happens a lot on Android, same here. CardField is rendered conditionally in BottomSheet by gorhom.
No time for making separate repository with the setup, so may be will try look into source of this lib. Good thing than hack with postalCode works.

**Comment by pavelglebov** [comment] 2022-11-27 18:09
**Found the issue**:

https://user-images.githubusercontent.com/5727746/204151265-361f5f7e-4140-4991-8c55-0619f184e656.mov

**So the issue is that postalCodeEnabled is true by default, and apply order of react props is not as expected (countryCode first which sets ```postalCodeRequired = true```, then postalCodeEnabled).**


Versions:
"react": "17.0.1",
"react-native": "0.64.3"


**Some additional investigation screens:**

<img width="400" alt="Screen Shot 2022-11-27 at 17 24 59" src="https://user-images.githubusercontent.com/5727746/204151481-fc610529-b65e-4a47-bd22-f722aadc55eb.png">
<img width="400" alt="Screen Shot 2022-11-27 at 18 00 54" src="https://user-images.githubusercontent.com/5727746/204151478-a978031c-4800-4d35-8d0b-49d582891190.png">


**How to fix locally (quick hack)**:

You need to re-trigger ```countryCode``` value after component render (while keeping ```postalCodeEnabled={true}``` - important):

<img width="400" alt="Screen Shot 2022-11-27 at 18 53 32" src="https://user-images.githubusercontent.com/5727746/204151744-86d6c069-4843-4442-97eb-36b6a4533348.png">


**PR with fix**:
https://github.com/stripe/stripe-react-native/pull/1213


@charliecruzan-stripe

**Comment by richardktran** [comment] 2023-05-18 10:49
This issue only happens with react-native version 0.64, after I update to 0.65, it will work as usual

**Comment by JalpeshDev** [comment] 2024-01-11 05:15
> Please provide a reproducible demo or code sample, otherwise it's very difficult to help. Tested this in [our example app](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/WebhookPaymentScreen.tsx) and it's working correctly.

Please check in android 10 and 11
