### ISSUE TITLE
PaymentSheet doesn't set in Customer the selected card

### ISSUE THREAD

**Issue by SrBrahma** [stripe/stripe-react-native#769] opened 2022-01-09 01:40 UTC
**Describe the bug**
If the user has multiple cards added via PaymentSheet, there isn't anywhere in the API that says what is the selected card.

Also, in https://stripe.com/docs/payments/save-and-reuse?platform=react-native&ui=payment-sheet#charge-saved-payment-method, it says to use `stripe.paymentMethods.list` to get the user payment methods. Ok, but if there are multiple methods, how do I know the one that the user has selected? This seems to be a major flaw in Stripe.

If I make my own way to set the default card, it will just be ambiguous to the user what really is the selected card, as in PaymentSheet it may has another card selected. What is the point of selecting another card in PaymentSheet and pressing `Set Up` and waiting for its loading if it doesn't do anything at all?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charliecruzan-stripe** [comment] 2022-02-11 23:01
closing as a duplicate of https://github.com/stripe/stripe-react-native/issues/716

**Closed by charliecruzan-stripe** 2022-02-11 23:01 UTC
