### ISSUE TITLE
Could not find constructor when recreating Activity

### ISSUE THREAD

**Issue by RafaRuiz** [stripe/stripe-react-native#930] opened 2022-05-09 14:04 UTC
**Describe the bug**
We are having some crash reports of some users:
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.flavouruat/com.example.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.reactnativestripesdk.PaymentLauncherFragment: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3774)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8184)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.reactnativestripesdk.PaymentLauncherFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:630)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:448)
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
        at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2410)
        at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2584)
        at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116)
        at androidx.fragment.app.FragmentActivity.lambda$init$1$FragmentActivity(FragmentActivity.java:128)
        at androidx.fragment.app.-$$Lambda$FragmentActivity$QtiQ2ZI3e38UkO1_xuJ8vE_JZj4.onContextAvailable(Unknown Source:2)
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:352)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249)
        at io.flutter.embedding.android.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:252)
        at android.app.Activity.performCreate(Activity.java:8129)
        at android.app.Activity.performCreate(Activity.java:8109)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3743)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:344) 
        at android.app.ActivityThread.main(ActivityThread.java:8184) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: java.lang.NoSuchMethodException: com.reactnativestripesdk.PaymentLauncherFragment.<init> []
        at java.lang.Class.getConstructor0(Class.java:2363)
        at java.lang.Class.getConstructor(Class.java:1759)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:615)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
        at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:448) 
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81) 
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
        at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2410) 
        at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2584) 
        at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116) 
        at androidx.fragment.app.FragmentActivity.lambda$init$1$FragmentActivity(FragmentActivity.java:128) 
        at androidx.fragment.app.-$$Lambda$FragmentActivity$QtiQ2ZI3e38UkO1_xuJ8vE_JZj4.onContextAvailable(Unknown Source:2) 
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:352) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249) 
        at io.flutter.embedding.android.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:252) 
        at android.app.Activity.performCreate(Activity.java:8129) 
        at android.app.Activity.performCreate(Activity.java:8109) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3743) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3936) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:344) 
        at android.app.ActivityThread.main(ActivityThread.java:8184) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
```

**To Reproduce**
Recreating an Activity can be tricky, but when you leave the app a long time in idle and come back to it, it usually happens.

Also, when switching the developer options "Don't keep activities", going into the app, and then passing it to background and foreground, it can be reproduced this way too.

**Expected behavior**
Fragments should have a default constructor and a way to recreate.

**Smartphone (please complete the following information):**
 - Device: happening in every device tested
 - OS: Any Android, tested (11, 12…)

**Comment by RafaRuiz** [comment] 2022-05-09 14:07
By the way, I'm using Flutter, but the sdk is linked to this one

**Comment by RafaRuiz** [comment] 2022-05-09 16:04
https://user-images.githubusercontent.com/6842786/167450723-53f98870-c2ad-448c-b5bd-f5a2e45d8af8.mp4

**Comment by RafaRuiz** [comment] 2022-05-09 16:54
This is because the Fragment `PaymentLauncherFragment` is being added to the `FragmentManager` at initialization (inflating a view and not showing it until requested, sounds like an antipattern).

It gets added with the tag `"payment_launcher_fragment"` 

Thankfully since I'm not using this Fragment right now, I remove this natively from the top through:

```
    final Fragment possibleStripeFragment = getSupportFragmentManager().findFragmentByTag("payment_launcher_fragment");
    if (possibleStripeFragment != null) {
        getSupportFragmentManager().beginTransaction().remove(possibleStripeFragment).commitAllowingStateLoss();
    }
```

but this is NOT a solution. Please I urge to fix that as soon as possible. Inflate the Fragment whenever it's going to be used only.

**Comment by charliecruzan-stripe** [comment] 2022-05-09 22:11
> Inflate the Fragment whenever it's going to be used only.

We're moving to this pattern, it came up through another issue we saw. However, I've seen this crash before and it was caused by another dependency (react-native-screens). although im guessing you don't have that installed as it's a flutter project?

**Comment by RafaRuiz** [comment] 2022-05-10 07:02
> although im guessing you don't have that installed as it's a flutter project?

No, I'm not using that. I came here because it's the native dependency that the Flutter library is using.
Using resources, inflating views, and adding it to the Fragment Manager is eating a deer before hunting it (apologies for vegans - it's just an expression). It uses resources that probably won't be ever shown and that's just wrong.

**Comment by diegobsit** [comment] 2022-05-16 10:04
Hi,

**Comment by diegobsit** [comment] 2022-05-16 10:10
Hi,

I'm facing the same issue with Flutter Stripe in production environment with thousands of crash reports in the last few days and i need to find a solution for this.

I was wondering if @RafaRuiz if you could provide more information on where you remove the fragment. I'm not using it either for the moment but I have no knowledge on Kotlin & Java so I can't figure out where I should add your code sample to work around this issue while it gets fixed.

Cheers

**Comment by droplessjake** [comment] 2022-05-18 13:28
+1 We are having customer report this issue and have been able to reproduce it using Rafa's method:
> Also, when switching the developer options "Don't keep activities", going into the app, and then passing it to background and foreground, it can be reproduced this way too.

We are not using flutter in our project however..

**Comment by droplessjake** [comment] 2022-05-18 13:48
Ah of course (completely missed that from my phone) Amazing, thanks for your help!

**Closed** 2022-06-01 14:15 UTC
Labels: android, In progress

**Comment by BobbyBorisov** [comment] 2022-06-20 08:32
Hi, I am on version `0.12.0` and still experiencing this issue? Anybody else?
