### ISSUE TITLE
CardField giving null in all keys of error and paymentIntent is also undefined

### ISSUE THREAD

**Issue by jdarshan5** [stripe/stripe-react-native#1064] opened 2022-07-28 10:30 UTC
**Describe the bug**
I am getting **{"code": "Failed", "declineCode": null, "localizedMessage": null, "message": null, "stripeErrorCode": null, "type": null}** error from confirmPayment function while using CardField.
I am passing this data to CardField:
`
CardNumber: 4242 4242 4242 4242,
expiryDate: 12/23,
cvc: 123,
postalCode: 123456,
`

**Smartphone (please complete the following information):**
 - Device: Vivo v9
 - OS: Funtouch OS

**Versions**
 - "react": "17.0.2"
 - "react-native": "0.65.0"
 - "@stripe/stripe-react-native": "^0.16.0"

**Comment by charliecruzan-stripe** [comment] 2022-07-28 19:10
Please provide a reproducible demo, not able to reproduce this myself so far

**Comment by jdarshan5** [comment] 2022-07-29 12:19
**At app.js**
`
import { StripeProvider } from '@stripe/stripe-react-native';
`
`
//in main function
`
`
<StripeProvider publishableKey='[PUBLISHABLE_TEST_KEY]' >
//Other Code
</StripeProvider>
`

**Confirming Payment**
`
import { CardField, useConfirmPayment } from '@stripe/stripe-react-native';
`
`
const {confirmPayment, loading} = useConfirmPayment();
`
`
const handlePayPress = async () => {
    if (!card) {
      return;
    }

    // Fetching the intent client secret from the backend.
    const clientSecret = await fetchPaymentIntentClientSecret();
const { error, paymentIntent } = await confirmPayment(clientSecret, {
paymentMethodType: 'Card',
            paymentMethodData: {
              billingDetails: {
                name: 'Blah Blah',
                email: '[EMAIL]',
                phone: '[MOBILE_NUMBER]',
                address: {[ADDRESS_OBJECT]}
              },
            },
          });
          if(error) {
            console.error(
              'Payment confirmation error', 
              error, 
            );
          } else if (paymentIntent) {
            console.log('Success from promise', paymentIntent);
          }
};
`
`
<CardField
              postalCodeEnabled={true}
              placeholders={{
                number: '4242 4242 4242 4242',
              }}
              cardStyle={{
                backgroundColor: '#FFFFFF',
                textColor: '#000000',
              }}
              style={{
                height: 50,
                marginVertical: 30,
              }}
              onCardChange={(cardDetails) => {
                console.log('cardDetails', cardDetails);
              }}
              onFocus={(focusedField) => {
                console.log('focusField', focusedField);
              }}
              autofocus
            />
<Button onPress={handlePayPress} title="Pay" disabled={loading} />
`

**Comment by charliecruzan-stripe** [comment] 2022-07-29 20:08
This works in the example screen [here](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/WebhookPaymentScreen.tsx), you might want to try and model your code off of that to figure out what's going on.

**Comment by charliecruzan-stripe** [comment] 2022-08-09 16:34
Closing since no repro was provided, but can re-open if there is one

**Closed by charliecruzan-stripe** 2022-08-09 16:34 UTC
Labels: reproduce
