### ISSUE TITLE
Visa/MasterCard icon onClick App Crash Issue ___Payment Page - Beside Card number Enter Field

### ISSUE THREAD

**Issue by ShobhitGalaxy2021** [stripe/stripe-react-native#1005] opened 2022-06-21 13:26 UTC
**Describe the bug**
On the payment page, under the card number field section, when the user clicks on the VISA/mastercard icon, the app crashes.

**To Reproduce**
1. Go to Payment Page --> Card Number entering Section
2. Click on Visa/masterCard icon just beside the card number entering section
3. Once the user Clicks the icon, the app crashes in android and ios

**Expected behavior**
App shouldn't crash when clicked on the VISA/MasterCard icon.

**Smartphone (please complete the following information):**
 - Device: Samsung M31
 - OS: Android
 - Version 11

**Comment by charliecruzan-stripe** [comment] 2022-06-22 17:46
It looks like this is working on the most recent version: 


https://user-images.githubusercontent.com/97612659/175102728-4254cbd7-5790-4d73-9603-f0a049a2225c.mov



https://user-images.githubusercontent.com/97612659/175102998-6a800829-67d3-4f37-a3d7-d383ca9096dd.mov




Going to close this since this issue doesn't contain the information we need/ask for in the template in order to help. Happy to reopen if you can provide a reproducible demo on the most recent version

**Closed as completed by charliecruzan-stripe** 2022-06-22 17:46 UTC
Labels: invalid

**Comment by ShobhitGalaxy2021** [comment] 2022-06-23 06:43
hi @charliecruzan-stripe its working first time when we try to re-subscribe and click on card app crash

**Comment by charliecruzan-stripe** [comment] 2022-06-23 13:12
Can you provide a minimal reproducible demo?
