### ISSUE TITLE
Google asking for save credit card every time in android

### ISSUE THREAD

**Issue by trigonometric-act** [stripe/stripe-react-native#790] opened 2022-02-02 12:58 UTC
Google asking for save credit card every time in android, no possiblity of deny. If I tap in the save option nothing happens, If I tap the "no thanks" option it shows the next time I pay with credit card.

1. Create app with react native latest version, 
2. yarn add @stripe/stripe-react-native": "^0.2.3",
3. Confirm a card payment with Stripe React Native
4. Use android device.

I expect a way to configure the plugin provider to not show the modal at all.

.
![IMG-20220131-WA0013](https://user-images.githubusercontent.com/47249028/152156686-969465f7-53ab-4fab-8a3a-0a699161311c.jpg)

**Comment by charliecruzan-stripe** [comment] 2022-06-01 20:59
duplicate of https://github.com/stripe/stripe-react-native/issues/616

**Closed by charliecruzan-stripe** 2022-06-01 20:59 UTC
