### ISSUE TITLE
[Payment sheet] Google Pay not showing when setupIntentClientSecret provided

### ISSUE THREAD

**Issue by trex-quo** [stripe/stripe-react-native#317] opened 2021-06-07 22:27 UTC
**Describe the bug**
When initializing the payment sheet on Android with a `setupIntentClientSecret` instead of a `paymentIntentClientSecret`, Google Pay does not appear on the Payment Sheet. When a `paymentIntentClientSecret` is provided, Google Pay does appear on the Payment Sheet. I have confirmed that I am correctly providing a Setup Intent and Payment Intent to their respective fields. 

**To Reproduce**
```
  const onSubscribePressAndroid = async () => {
    const res = await functions().httpsCallable('getStripeSecret')({});
    if (res.data.errorCode) {
      console.log(res.data.errorCode);
      return;
    }

    const secret = res.data.setupIntentSecret;

    let {error} = await initPaymentSheet({
      setupIntentClientSecret: secret, //providing a Payment Intent to paymentIntentSecret makes Google Pay appear on the payment sheet
      googlePay: true,
      merchantCountryCode: 'US',
      merchantDisplayName: 'Quo Finance',
      testEnv: true,
    });

    if (error) {
      console.log({error});
      return;
    }

    await sleep(1000);

    try {
      ({error} = await presentPaymentSheet({
        clientSecret: secret,
      }));
    } catch (e) {
      console.log({e});
      updateLoading(false);
      return;
    }


    if (error) {
      console.log({error});
      return;
    }
  };
```

**Expected behavior**
I would expect Google Pay to appear on the Payment Sheet regardless of whether or not a Setup Intent or Payment Intent is provided.

**Screenshots**
With Payment Intent provided:
![Screenshot_20210607-151906_Quo](https://user-images.githubusercontent.com/75281449/121095161-a747da00-c7a4-11eb-8a73-af7a803139a2.jpg)

With Setup Intent provided:
![Screenshot_20210607-151938_Quo](https://user-images.githubusercontent.com/75281449/121095167-ac0c8e00-c7a4-11eb-81a7-1c328de1e951.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.2.3

**Smartphone (please complete the following information):**
 - Device: Galaxy S10
 - OS: Android

**Comment by thorsten-stripe** [comment] 2021-06-08 09:01
I'm able to reproduce this. Will check with the team.

**Comment by thorsten-stripe** [comment] 2021-06-10 03:45
This is currently not supported in `stripe-android`. We will need for a new release of the `stripe-android` SDK to ship this functionality.

**Comment by ScreamZ** [comment] 2022-05-10 11:36
@thorsten-stripe Is it supported now? @trex-quo Currently I've made two separated buttons.
@Mfrizzy FYI

**Comment by charliecruzan-stripe** [comment] 2022-08-12 22:44
This was fixed in stripe-android a while ago, and we've since integrated that version into stripe-react-native, so I'm going to close this issue

**Closed by charliecruzan-stripe** 2022-08-12 22:44 UTC
Labels: enhancement, blocked
