### ISSUE TITLE
Update Google Pay Icon

### ISSUE THREAD

**Issue by antoinerousseau** [stripe/stripe-react-native#1082] opened 2022-08-09 13:47 UTC
**Describe the bug**

The appearance of `<GooglePayButton />` does not fit Google guidelines anymore.
After integrating it, I got this message after submitting for review:

> Hi,
> 
> We have an update on your recent Google Pay API integration submission.
> 
> We need more information about com.shotguntheapp.android:
> Please update to our approved [Google Pay mark](https://developers.google.com/pay/api/android/guides/brand-guidelines#google-pay-logo-mark) and [Google Pay button](https://developers.google.com/pay/api/android/guides/brand-guidelines#payment-buttons). Note, our android brand guidelines have recently been updated. 
> 
> Please make the appropriate updates, and re-submit your integration again through the Google Pay & Wallet Console. If the above marketing review feedback cannot be implemented because you are using a dedicated Plugin or provided hosted checkout solution from your Payment Service Provider, please reach out to us by responding to this email.
> 
> Thank you for submitting your integration through the Google Pay & Wallet Console. It’s been a pleasure working with you.
> 
> 
> Best,
> Angie
> The Google Pay API Support Team

I had to download and integrate their SVG but the best would be to integrate it to this lib.

**Comment by charliecruzan-stripe** [comment] 2022-08-09 16:27
duplicate of https://github.com/stripe/stripe-react-native/issues/1068

**Closed by charliecruzan-stripe** 2022-08-09 16:27 UTC
