### ISSUE TITLE
Request shipping address from Google Pay and Apple Pay

### ISSUE THREAD

**Issue by simona-iuliana** [stripe/stripe-react-native#979] opened 2022-06-07 14:27 UTC
Is there a way to get the shipping address from your wallet ( google pay/ apple pay)?
I saw we can request it on Apple Pay, but not been returned by `presentApplePay` hook. Also on Google Pay we can request only the billing address. This is a bit annoying because my expectation as a user would be that if I'm using Apple Pay that both the card are shipping addresses are all handled inside the native Apple Pay and returned to me so I can use them in the app.

**Comment by charliecruzan-stripe** [comment] 2022-06-22 17:09
Looks like this is a duplicate of https://github.com/stripe/stripe-react-native/issues/580, which we've got in our backlog 👍

**Closed by charliecruzan-stripe** 2022-06-22 17:09 UTC
