### ISSUE TITLE
Postal Code field is differently visible for the same countries on Android and iOS

### ISSUE THREAD

**Issue by AlexSirenko** [stripe/stripe-react-native#679] opened 2021-10-26 13:59 UTC
**Describe the bug**
Postal Code field is differently visible for the same countries on Android and iOS

**To Reproduce**
Open CardForm on IOS and Android

**Expected behavior**
Postal Code should have the same behavior on Android and iOS

**Comment by charliecruzan-stripe** [comment] 2022-03-16 16:31
duplicate of https://github.com/stripe/stripe-react-native/issues/752

**Closed by charliecruzan-stripe** 2022-03-16 16:31 UTC
Labels: reproduce
