### ISSUE TITLE
Android: App requires prominent disclosure. What info does this package collect?

### ISSUE THREAD

**Issue by multiplegeorges** [stripe/stripe-react-native#578] opened 2021-09-09 14:18 UTC
**Describe the bug**
This package and its documentation does not make it clear what info it collects and returns to Stripe.

**To Reproduce**
1. Integrate this package with your RN project.
2. Generate an app bundle and submit it to Google Play
3. Get a notice from Google.

**Expected behavior**
A clear and transparent full disclosure in the docs about what info is collected, why Stripe collects it, and an example of how to address it so that our apps conform to the store requirements.

**Screenshots**
<img width="776" alt="Screen Shot 2021-09-09 at 10 13 33 AM" src="https://user-images.githubusercontent.com/59541/132702812-a5ce6661-3daf-4325-8072-eade0c4d2858.png">

**Smartphone (please complete the following information):**
Android, and probably iOS as well. 

**Additional context**
Related to this, what disclosure should we be adding to our App Store Privacy card for the iOS version of the app?

Guidance from Stripe on this is needed.

Thanks!

**Comment by michelleb-stripe** [comment] 2021-09-13 11:56
@multiplegeorges There are previous versions of the Stripe library that were causing this issue.  

- If you're integrating an old version of the SDK, we've provided hotfixes so you can easily upgrade:
        - 9.x → 9.4.0
        - 10.x → 10.5.0
        - 11.x → 11.3.0
        - 12.x → 12.9.0
        - 13.x → 13.3.0
- If you're using tipsi-stripe, you must upgrade to v9.1.0+ (it depends on 16.10.0 of the android-sdk, anything before that depends on a violating version of the SDK)
- You don't have older versions of your app bundled in your active release (to support older Android versions, for example)
- You don't have older versions of your app available in testing tracks on Google Play Console.

![image](https://user-images.githubusercontent.com/77996191/133079174-a29d0e81-0258-4e2a-86ca-23be88df2566.png)

**Comment by ilyagru** [comment] 2021-09-23 12:36
I tried re-submit my app with the latest package version 0.2.2 but getting the same rejection from Google Play. Any ideas what else could be missing?

**Comment by YoQuieroDistraerlo** [comment] 2021-09-23 13:33
Hey @ilyagru can you share the content of the 'dependencies' section of you app/build.gradle file?
This is what I have for the stripe sdk:

```gradle
dependencies {
    
    implementation 'com.stripe:stripe-android:17.1.1'
    
}
```

**Comment by ilyagru** [comment] 2021-09-23 13:35
@YoQuieroDistraerlo I'm using @stripe/stripe-react-native package with the latest version which uses 'com.stripe:stripe-android:17.1.1', so yes.

**Comment by YoQuieroDistraerlo** [comment] 2021-09-23 13:44
Hey @michelleb-stripe @trag-stripe can you acknowledge what Google Play reviewers are saying or, provide us with an explanation or statement we can present to them?
Thank you!

**Comment by multiplegeorges** [comment] 2021-09-23 14:20
Yeah, my updated app on 0.2.2 was also rejected.
My `app/build.gradle` doesn't specify a `stripe-android` dependency, but my `node_modules/@stripe/stripe-react-native/android/build.gradle` has:

```
dependencies {
  ...
  implementation 'com.stripe:stripe-android:17.1.0'
  ...
}
```

**Comment by michelleb-stripe** [comment] 2021-09-23 14:48
@YoQuieroDistraerlo I apologize that you are still having issues, and we would like to work with you to remove any problems associated with the Android SDK. 


1. Is your message from Google identical to the one reported by @multiplegeorges?
 
2. I want to make sure that an old stripe-android version isn't being included in another way.  Can you open the Android project in Android Studio, open the File -> Project Structure, then click on Dependencies in the left pane.   If you can look through <All modules> in your project and verify that no other versions of stripe-android are included?

3. In regards to the Google Play Console:
   a. Does the updated version of your app have an updated version number and version code?
   a. Were you able to upload a version of your app with the updated react-native library to all the tracks: production, open, closed, and internal?
   c. Is your app the only active version in each of the tracks: production, open, closed, and internal?
   d. Were you able to upload a version of your app with the updated library to all the tracks: production, open, closed, and internal?

**Comment by YoQuieroDistraerlo** [comment] 2021-09-23 14:53
I’m about to send my app for review with this new library but haven’t yet. I’m concerned about @ilyagru reported issue.
Let’s wait for additional comments from @ilyagru.

**Comment by ilyagru** [comment] 2021-09-24 07:54
@michelleb-stripe @YoQuieroDistraerlo Yes, I'm a bit confused too, to be honest. At our company, we've got the Staging version of the app which we are testing through the Internal track on Google Play. We are using only one track currently for the app. All tracks are inactive now. Everything was fine but unexpectedly it got removed from Google Play with a similar message.

At the moment of removal, the version of "@stripe/stripe-react-native" was "^0.1.4" (which is also fine?), then I updated it to the latest  "^0.2.2" and re-submitted the app but the update got rejected as well.

I just went through the dependencies, it has only `stripe-android:17.1.0.

I see some other people started to experience this issue too https://stackoverflow.com/questions/69072021/stripe-android-sdk-doesn-t-comply-with-the-user-data-and-mobile-unwanted-softwar

Could it be a problem with the privacy policy not being precise then? But if those bits causing the issue are removed from the Stripe package, what should be put in there in this case? 

<img width="534" alt="Screenshot 2021-09-24 at 09 34 36" src="https://user-images.githubusercontent.com/18074511/134636543-3b7f7d62-0f21-4987-904d-fd6ced3a1507.png">
<img width="381" alt="Screenshot 2021-09-24 at 09 45 28" src="https://user-images.githubusercontent.com/18074511/134638206-91519b42-3383-4e5f-911f-0ddb15084503.png">
<img width="374" alt="Screenshot 2021-09-24 at 09 46 29" src="https://user-images.githubusercontent.com/18074511/134638210-7b0588cf-5a5f-494f-a1af-cb562804cd75.png">

**Comment by michelleb-stripe** [comment] 2021-09-24 18:30
@ilyagru Let me reach out to you directly on email, and we will report back here with more information.

**Comment by michelleb-stripe** [comment] 2021-09-24 19:11
@ilyagru One more thing for you to check in your Google Play Console.  In the Google Play Console you can click on a release and see all the App Bundles associated with it.  Can you compare the App Bundle ID shown in the Google Play Console with the App Bundle ID in the email: 15735757 and make sure they match?

**Comment by ilyagru** [comment] 2021-09-27 08:21
@michelleb-stripe yes, of course they match. Please write to me ilya.gruzhevski@zego.com.

**Comment by ilyagru** [comment] 2021-09-27 08:29
@michelleb-stripe it looks like Google requires us to update the privacy policy to disclose that we are using Stripe which might be collecting `Installed Application and Phone Number information`. Could you please specify or give a link to Stripe's privacy policy where it is described? But quite confusing that you are saying you don't collect that information but Google is saying you do...

**Comment by ilyagru** [comment] 2021-09-28 12:53
The issue was with another track on Google Play where there was an older build with the outdated SDK. Although the channel was inactive, Google takes all channels into account while reviewing - that was quite confusing bit. I managed to solve it by updating that track as well.  Thanks for help!

**Comment by Hadi-G** [comment] 2021-10-14 06:37
> Google Play where there
@ilyagru which track was concerned ? I have the same issue with the play store. I have created a release only in production track, and my updates are rejected for the same reasons ...  I don't know what i'm missing.

**Comment by cebrakadabra** [comment] 2021-11-17 17:53
> @ilyagru One more thing for you to check in your Google Play Console. In the Google Play Console you can click on a release and see all the App Bundles associated with it. Can you compare the App Bundle ID shown in the Google Play Console with the App Bundle ID in the email: 15735757 and make sure they match?

Ultimately this comment is what it solved it for me.
Once I looked at the Email again and compared version codes, it happened to be a `internal testing` app we release over a year ago that was on a paused track. Really misleading and very aggressive to get removed for an internal testing app apk that is much older than the current release.

Thanks for pointing that out!

**Comment by martinschuberts** [comment] 2021-12-09 18:17
Same for me - the problem was with a old track/release! Thanks for that hint!

**Comment by gmontemayor1987** [comment] 2022-01-19 22:17
Same problem here, @michelleb-stripe I'm using tipsi-stripe which is using v16.10.0
Do you know if we have to patch tipsi stripe with a new version?

**Comment by charliecruzan-stripe** [comment] 2022-02-09 14:48
Closing this issue since the problem was caused by older releases on different tracks. 

> One more thing for you to check in your Google Play Console. In the Google Play Console you can click on a release and see all the App Bundles associated with it. Can you compare the App Bundle ID shown in the Google Play Console with the App Bundle ID in the email: 15735757 and make sure they match?

> The issue was with another track on Google Play where there was an older build with the outdated SDK. Although the channel was inactive, Google takes all channels into account while reviewing - that was quite confusing bit. I managed to solve it by updating that track as well. Thanks for help!

> Once I looked at the Email again and compared version codes, it happened to be a internal testing app we release over a year ago that was on a paused track. Really misleading and very aggressive to get removed for an internal testing app apk that is much older than the current release.

**Closed by charliecruzan-stripe** 2022-02-09 14:48 UTC
