### ISSUE TITLE
One additional click to move the focus on Android 

### ISSUE THREAD

**Issue by BobbyBorisov** [stripe/stripe-react-native#1086] opened 2022-08-12 08:20 UTC
Hi,

I am using the `<CardField>` component but I have issue with it.. I fill all the data (card number, expiration date, cvc) and when i finish (the cursor is at cvc field) I tab outside the form on the screen, the cursor moves to the card number field and I need to tab one more time (on my button or just outside of the form) in order to move the focus away from the form. 

**Expected behavior**
I guess we only need one tab outside of the form in order to move the focus away and be able to click the button to add the card. On iOS it seems to work fine. I need 2 tabs to work, on Android I need 3

 - OS: Android emulator

Thanks in advance!

**Comment by charliecruzan-stripe** [comment] 2022-08-12 16:06
I think this might be the same as https://github.com/stripe/stripe-react-native/issues/222

Are you using `<StripeContainer/>` ?

**Comment by charliecruzan-stripe** [comment] 2022-08-16 23:16
Closing as a duplicate of #222, this has been fixed with the introduction of the `StripeContainer` :)

**Closed by charliecruzan-stripe** 2022-08-16 23:16 UTC
Labels: question
