### ISSUE TITLE
Programatically update CardField variables

### ISSUE THREAD

**Issue by MaxRobertsDear** [stripe/stripe-react-native#1257] opened 2023-01-11 20:04 UTC
**Is your feature request related to a problem? Please describe.**
Have implemented a custom card scanner, given that stripe's equivalent only supports iOS. Want to populate the CardField props for number and expiry date based on the result of the card scanner.

**Describe the solution you'd like**
A simple way of updating the `value`, the same way you would a `TextInput` (for example). Or even a way to expose the components such that they can be updated via `ref.current.setNativeProps()`.

**Comment by charliecruzan-stripe** [comment] 2023-01-11 20:10
Hi! Closing this as a duplicate of https://github.com/stripe/stripe-react-native/issues/637

**Closed by charliecruzan-stripe** 2023-01-11 20:10 UTC
