### ISSUE TITLE
Android Crash: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by goguda** [stripe/stripe-react-native#887] opened 2022-04-14 15:51 UTC
![image](https://user-images.githubusercontent.com/26887502/163402551-ce882444-e25e-4a19-b327-a11e4ef7f34f.png)

Causing several crashes per day on Android.

Based on Breadcrumbs I believe this is causing a crash after the app is re-opened from a background state:

![image](https://user-images.githubusercontent.com/26887502/163402832-9949e429-a864-4dcb-9371-5b87a3a814a4.png)

(CodePush check only runs after app is brought back to foreground from a background state)

Based on a quick google search, it seems this is a fairly common Android issue.

One possible solution would be to change .commit() to .commitAllowingStateLoss(), but it appears this is more of a bandaid solution that could result in the user being brought to an unexpected screen.

In this case though, since it's in the initialize() function, I don't think the user is actually being shown anything and it may be safe in this case? (although I could be wrong)

The other way to fix it, if this is not safe, appears to be to use lifecycle components (third answer down).

Source: https://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit

**Comment by charliecruzan-stripe** [comment] 2022-04-18 19:52
What version of `stripe-react-native` is this using?

**Comment by professorkolik** [comment] 2022-04-23 18:34
@charliecruzan-stripe 
`"@stripe/stripe-react-native": "^0.7.0",` and `"@stripe/stripe-react-native": "^0.6.0",`
`"react-native": "0.68.1",`

android/build.gradle
`buildToolsVersion = "31.0.0"`
`minSdkVersion = 24`
`compileSdkVersion = 31`
`targetSdkVersion = 31`

android/app/build.gradle

`
dependencies {
   implementation 'com.stripe:stripe-android:20.1.+'
}
`

Crashlytics stacktrace attached

<img width="1232" alt="Screenshot 2022-04-23 at 20 31 27" src="https://user-images.githubusercontent.com/7031202/164936482-501ea78d-8e06-458f-819d-d228b3d87180.png">

@charliecruzan-stripe Please lmk if you need more info

**Comment by charliecruzan-stripe** [comment] 2022-04-25 14:24
> dependencies { implementation 'com.stripe:stripe-android:20.1.+' }

You don't need to declare the native stripe android dependency. In fact, I'd recommend against doing that and just letting stripe react native handle it.

**Comment by professorkolik** [comment] 2022-04-25 19:56
@charliecruzan-stripe thank you for quick response
1. Do you think removing this line from dependencies might resolve the crashes?
2. This line `dependencies { implementation 'com.stripe:stripe-android:20.1.+' }` is part of the documentation to set up Google Pay https://stripe.com/docs/payments/accept-a-payment#react-native-google-pay

**Comment by charliecruzan-stripe** [comment] 2022-04-26 16:07
1. I don't believe so. we have the same version pinned in our library, it just could cause issues later on
2. Good catch! I will fix that

**Comment by professorkolik** [comment] 2022-04-26 19:16
@charliecruzan-stripe great thanks, I'll remove the dependency

Regarding the crash, any ideas, should we create an issue on `stripe-android`?

**Comment by goguda** [comment] 2022-04-26 19:44
I've got 39 crashes from 34 users on Android logged from versions 0.5.0 to 0.7.0 of stripe-react-native.

I also haven't been declaring the dependency manually in build.gradle (I've just let stripe-react-native handle it as intended), so that rules that out.

Each and every crash occurs right after the app is brought to foreground from background state, so that indicates to me it is indeed a lifecycle issue.

Based on my research, I truly believe the only proper way of fixing this is to modify line 246 in StripeSdkModule.kt as I described above.

Kotlin and native Android development are not my specialty, but since this one seems to be a relatively serious and persistent bug, I'm going to do a bit more research and see if I can get a PR together relatively soon.

**Comment by professorkolik** [comment] 2022-04-26 20:59
@goguda We don't use CodePush, and I'm pretty confident that this crash is not caused by it.
For the stats we have 176 crashes out of 189 users

**Comment by professorkolik** [comment] 2022-04-26 21:02
@charliecruzan-stripe how can we escalate this problem to get higher priority? From what I see it doesn't affect user flow to pay, but has high impact on our users satisfaction about the product

**Comment by charliecruzan-stripe** [comment] 2022-04-26 21:45
@professorkolik yeah I see what you mean. If you're able to repro this without codepush, do you think you can give me a set of steps to follow to do so? If I can repro, I'm sure I can push out a fix asap

**Comment by professorkolik** [comment] 2022-04-26 22:31
@charliecruzan-stripe sure below is the lifecycle
Happens on various android OS versions from 8 to 11

Also `hermes` is enabled if that make any difference

<img width="999" alt="Screenshot 2022-04-27 at 00 27 22" src="https://user-images.githubusercontent.com/7031202/165403202-d83bed63-66b3-4004-930d-ef15cdcd17b4.png">

**Comment by goguda** [comment] 2022-04-26 22:58
> @charliecruzan-stripe sure below is the lifecycle Happens on various android OS versions from 8 to 11
> 
> Also `hermes` is enabled if that make any difference
> 
> <img alt="Screenshot 2022-04-27 at 00 27 22" width="999" src="https://user-images.githubusercontent.com/7031202/165403202-d83bed63-66b3-4004-930d-ef15cdcd17b4.png">

Hermes too, identical logs in Sentry

Hmm, this is an interesting one... was trying to see if there was any sort of user sequence or something in my Matomo logs that was causing it but it really does seem to be completely random. In fact my users haven't even interacted with any sort of Stripe APIs, other than StripeProvider wrapping the app.

**Comment by professorkolik** [comment] 2022-04-29 11:12
@charliecruzan-stripe hello, any news about this issue?

**Comment by charliecruzan-stripe** [comment] 2022-05-05 21:11
I haven't been able to repro this yet, but looking at our use of `.commit()`, I think we can replace some instances with `commitAllowingStateLoss`, and then in the cases where we shouldn't do so, catch the error and reject the promise. 

Just curious, have you tried the fix [here](https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067)?

**Comment by goguda** [comment] 2022-05-06 04:45
> I haven't been able to repro this yet, but looking at our use of `.commit()`, I think we can replace some instances with `commitAllowingStateLoss`, and then in the cases where we shouldn't do so, catch the error and reject the promise.
> 
> Just curious, have you tried the fix [here](https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067)?

Yes my app implements this fix but I'm still getting the crash.

This is a tough one, I haven't been able to reproduce it myself either but I'm getting substantial logs for it.

I've done some research on commit and commitAllowingStateLoss. This is a good article summarizing it: 

https://medium.com/inloopx/demystifying-androids-commitallowingstateloss-cb9011a544cc

The discussion in the fix you linked discusses the behaviour of a react native app when the process is killed and has to be restarted on Android. In the context of a react native app, since the whole app is contained within a single activity, if the process is killed the RN app is restarted, the sdk is reinitialized from the js layer and any user actions have to be performed again anyways. commitAllowingStateLoss should be safe in all contexts since the sdk is controlled from the js layer.

PR #927

**Comment by professorkolik** [comment] 2022-05-06 10:30
> I haven't been able to repro this yet, but looking at our use of `.commit()`, I think we can replace some instances with `commitAllowingStateLoss`, and then in the cases where we shouldn't do so, catch the error and reject the promise.
> 
> Just curious, have you tried the fix [here](https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067)?

Same here, this fix is implemented

![Screenshot 2022-05-06 at 12 25 25](https://user-images.githubusercontent.com/7031202/167114608-c5444e26-d705-4316-a659-2aa30d6fa321.png)

It's very high number of crashes in our product.

It's seems very easy to reproduce it
1. Use StripProvider
2. Implement PaymentsUICompleteScreen.tsx
3. Run app on physical Android device
4. Background the app
5. Foreground the app

**Comment by goguda** [comment] 2022-05-06 13:51
> > I haven't been able to repro this yet, but looking at our use of `.commit()`, I think we can replace some instances with `commitAllowingStateLoss`, and then in the cases where we shouldn't do so, catch the error and reject the promise.
> > Just curious, have you tried the fix [here](https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067)?
> 
> Same here, this fix is implemented
> 
> ![Screenshot 2022-05-06 at 12 25 25](https://user-images.githubusercontent.com/7031202/167114608-c5444e26-d705-4316-a659-2aa30d6fa321.png)
> 
> It's very high number of crashes in our product.
> 
> It's seems very easy to reproduce it
> 
>     1. Use StripProvider
> 
>     2. Implement PaymentsUICompleteScreen.tsx
> 
>     3. Run app on physical Android device
> 
>     4. Background the app
> 
>     5. Foreground the app

I actually don't think PaymentsUICompleteScreen.tsx is part of the problem, we're not using it at all in our app. In fact I haven't even had any users use the portion of our app yet that implements Stripe (it's a new app), so this means for me it is happening simply because the app is wrapped in StripeProvider.

I haven't been successful in reproducing it simply by backgrounding and foregrouding the app, but I've only tried in the simulator. Perhaps it does only happen on real devices.

**Comment by professorkolik** [comment] 2022-05-06 14:06
@goguda I just provide a rough sample of our config (PaymentsUICompleteScreen.tsx) just to give the direction
This issue you can reproduce on physical device.
May be I'll try it out and debug it on Android Studio to provide more info

**Comment by MaxJadav** [comment] 2022-05-09 04:05
Have you guys find any good solution?
I also getting  same crash for many users.
![Screenshot 2022-05-09 at 9 33 06 AM](https://user-images.githubusercontent.com/31030098/167338779-d2c97cad-18fa-4061-adaa-c01f4bd7d1e0.png)

**Comment by charliecruzan-stripe** [comment] 2022-05-09 19:33
Should be fixed by https://github.com/stripe/stripe-react-native/pull/933, I still haven't been able to reproduce this crash myself so if someone that is able to reproduce this crash reliably can try this out, please let me know. Happy to pair with you on it as well 😄

**Closed** 2022-05-10 15:20 UTC
Labels: question

**Comment by meet-bm-ai** [comment] 2023-11-17 14:27
@charliecruzan-stripe We faced this for a few users on our app. We are using stripe-react-native@0.33.0

Any idea why this could be re-surfacing?

**Comment by charliecruzan-stripe** [comment] 2023-11-17 17:19
Could you share the stacktrace?
