### ISSUE TITLE
Getting `length=0; index=0` as an error from presentGooglePay

### ISSUE THREAD

**Issue by developer-at-openbar** [stripe/stripe-react-native#633] opened 2021-10-07 20:01 UTC
**Describe the bug**
Wehn presentGooglePay is called with clientSecret with forSetupIntent: false, it shows response of ```{"error": {"code": "Failed", "declineCode": null, "localizedMessage": "length=0; index=0", "message": "length=0; index=0", "stripeErrorCode": null, "type": null}}```

Not sure what is wrong with it and what the error means

**To Reproduce**
1. Call initGooglePay and set constant as true when no error so google button shows up
2. Call createGooglePayPaymentMethod with amount and currencyCode
3. When no error, get the clientSecret from backend using paymentMethod id returned from createGooglePayPaymentMethod
4. Call `presentGooglePay` with client secret and forSetupIntent: false. 
5. Gets an error as below: ``{"error": {"code": "Failed", "declineCode": null, "localizedMessage": "length=0; index=0", "message": "length=0; index=0", "stripeErrorCode": null, "type": null}}```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
 - Version "@stripe/stripe-react-native": "^0.2.2",

**Additional context**

**Comment by arekkubaczkowski** [comment] 2021-10-11 06:33
@developer-at-openbar  sorry but those information are not enough, as I mentioned above, please provide the code snippet so I can verify if everything is fine there

**Comment by raquelmsmith** [comment] 2021-10-12 17:11
The problem I was having was that my server integration wasn't working properly. So make sure that's up and running properly.

**Comment by developer-at-openbar** [comment] 2021-10-13 16:22
@raquelmsmith Can you let me know in detail about the server integration? Does it mean backend setup has to be fixed? If yes, how did you fix it?

**Comment by raquelmsmith** [comment] 2021-10-13 17:07
I didn't do our server integration. My specific problem is that our backend engineer had set up the server side of it and I pulled it down locally, but I didn't apply the metadata for our db (Hasura), so it wasn't working. Once I applied the metadata, it was working properly. So I guess - check that you set up the server side of things properly: https://stripe.com/docs/payments/accept-a-payment?platform=react-native

And then if you're pulling down changes locally that someone else made, make sure they're being applied correctly. 

Other than that I don't have much help to offer, sorry!

**Comment by charliecruzan-stripe** [comment] 2022-03-18 20:52
Going to close this since it seems it's due to misconfiguring your server code. If you're getting this error message and can't seem to fix it, please share a way for us to reproduce it and we can try to help 😄

**Closed by charliecruzan-stripe** 2022-03-18 20:52 UTC

**Comment by leudy015** [comment] 2022-03-31 11:23
i am also getting the same error

export const payGooglePay = async (
  presentGooglePay,
  setInitialized,
  amount,
  currency,
  setLoading,
  customer,
) => {
  setLoading(true);
  // 2. Fetch payment intent client secret
  const paymentIntent = await fetchPaymentIntentClientSecret(
    amount,
    currency,
    customer,
  );

  const client_secret = paymentIntent.client_secret;
  // 3. Open Google Pay sheet and proceed a payment
  const {error} = await presentGooglePay({
    client_secret,
    forSetupIntent: false,
  });

  if (error) {
    Alert.alert(error.code, `${JSON.stringify(error)}`);
    return {
      succeed: false,
      paymentIntent: null,
    };
  } else {
    setInitialized(false);
    return {
      succeed: true,
      paymentIntent: paymentIntent,
    };
  }
};

**Comment by leudy015** [comment] 2022-03-31 11:25
![Screenshot_20220331-131533_Rentyt](https://user-images.githubusercontent.com/49622506/161044491-0f6fb8fb-1898-4f22-944a-b54c9fdaa347.jpg)
