### ISSUE TITLE
Invalid Email Address - createPaymentMethod on Android 

### ISSUE THREAD

**Issue by AdamLee321** [stripe/stripe-react-native#736] opened 2021-11-29 16:00 UTC
**Describe the bug**
When submitting the card details to Stripe using the createPaymentMethod function, an error is thrown. This is only happening on Android but is working fine on iOS.

```
async getPaymentMethod() {
  let {cardholderName} = this.state;

  let billingDetails = {
    name: cardholderName,
  };

  return createPaymentMethod({
    type: 'Card',
    billingDetails,
  }).then(result => {
    if (result.error) {
      throw result.error;
    }
    return result.paymentMethod;
  });
}
```

**To Reproduce**
1. Copy the above code.
2. Run on Android.
3. Trigger the function by passing card details.

**Expected behavior**
A payment method should be returned by Stripe but instead it is throwing an error.

**Screenshots**
<img width="374" alt="Screenshot 2021-11-29 at 15 51 33" src="https://user-images.githubusercontent.com/22890658/143900077-f66c71dc-af30-4bfa-bc18-60aa1c46e214.png">

<img width="315" alt="Screenshot 2021-11-29 at 15 49 12" src="https://user-images.githubusercontent.com/22890658/143900088-44e3b476-1ec7-4192-910d-d50a9d1fc76c.png">

**Additional Information**
"@stripe/stripe-react-native": "^0.2.3",
"react": "17.0.2",
"react-native": "0.66.0",

If any further information is needed please comment and I will added it as soon as possible.

**Comment by niraj-khatiwada** [comment] 2021-12-03 10:08
Same error.

**Comment by AdamLee321** [comment] 2021-12-03 10:27
> Same error.

If you find a solution can you please post your answer? I have tried to solve and have had no luck, this is definitely a bug.

**Comment by khanhnb0710** [comment] 2021-12-07 04:40
let try it man
`  let billingDetails = {
      name: cardholderName,
      email: "your-email@email.com", //here is your email
      phone: "123456789", //here is your phone number
    };`
    It work for me

**Comment by AdamLee321** [comment] 2021-12-07 08:11
Thanks for posting your solution. This will work as a temporary fix but email and phone number should not be required for creating a payment method. Unless they have become required recently?

**Comment by charliecruzan-stripe** [comment] 2022-02-02 16:29
Looking into this now, sorry for the late response! Trying to repro this, but so far I'm not able to trigger the error. 


<details open>
<summary>Really simple repro I'm using is below
</summary>
<br>

```jsx
import {CardField, useStripe} from '@stripe/stripe-react-native';
import React from 'react';
import {View, Button} from 'react-native';

export default function PaymentScreen() {
  const {createPaymentMethod} = useStripe();

  return (
    <View>
      <CardField
        style={{
          width: '100%',
          height: 50,
          marginVertical: 30,
        }}
      />
      <Button
        title={'press'}
        onPress={() => {
          let billingDetails = {
            name: 'cardholderName',
          };

          return createPaymentMethod({
            type: 'Card',
            billingDetails,
          }).then((result) => {
            if (result.error) {
              alert('error: ' + JSON.stringify(result.error));
              return;
            }
            alert('success: ' + JSON.stringify(result.paymentMethod));
            return result.paymentMethod;
          });
        }}
      />
    </View>
  );
}

```
</details>

```
  "dependencies": {
    "@stripe/stripe-react-native": "^0.2.3",
    "react": "17.0.2",
    "react-native": "0.66.4"
  },
```

**Comment by charliecruzan-stripe** [comment] 2022-02-11 20:22
Going to close this as a duplicate of https://github.com/stripe/stripe-react-native/issues/712

**Closed by charliecruzan-stripe** 2022-02-11 20:22 UTC
Labels: reproduce
