### ISSUE TITLE
None of the requested payment methods ([sepa_debit]) match the supported payment types ([card, bancontact, sofort, ideal, sepa_debit, eps, giropay, p24, klarna, paypal, afterpay_clearpay])

### ISSUE THREAD

**Issue by mahpgnaohhnim** [stripe/stripe-react-native#1069] opened 2022-08-01 12:27 UTC
I have setup a connect test account and activated all payments in Test-Mode.
Payment Intente created by backend has sepa_debit as the only PaymentMethodType.
Response from  initPaymentSheet is:
`{ "paymentOption": undefined,}`

and response in presentPaymentSheet:
`{
  "error": Object {
    "code": "Failed",
    "declineCode": null,
    "localizedMessage": "None of the requested payment methods ([sepa_debit]) match the supported payment types ([card, bancontact, sofort, ideal, sepa_debit, eps, giropay, p24, klarna, paypal, afterpay_clearpay])",
    "message": "None of the requested payment methods ([sepa_debit]) match the supported payment types ([card, bancontact, sofort, ideal, sepa_debit, eps, giropay, p24, klarna, paypal, afterpay_clearpay])",
    "stripeErrorCode": null,
    "type": null,
  },
}`

Is there a way to use payementSheet with sepa_debit in test-mode?
Having giropay or card in PaymentMethodType is working.
Using stripe.confirmPayment instead of initPaymentSheet() and presentPaymentSheet() is working too.

code snippet:
`stripe.initPaymentSheet({
                     merchantDisplayName: companyName'',
                     paymentIntentClientSecret: res.data.result.clientSecret,
                 }).then(resp => {
                     console.log('resp', resp);
                     stripe.presentPaymentSheet().then(respo => {
                         console.log('respo', respo);
                     }).catch(err => {
                         console.log('err', err);
                     })
                 }).catch(e => {
                     console.log('e', e);
                 })`

**Comment by charliecruzan-stripe** [comment] 2022-08-04 20:38
> Is there a way to use payementSheet with sepa_debit in test-mode?

Yes, it works with our example app:

<img width="378" alt="Screen Shot 2022-08-04 at 1 37 33 PM" src="https://user-images.githubusercontent.com/97612659/182947985-65c4376e-294e-46c3-b0f1-33cbd347e8e7.png">


I would recommend double-checking you're creating the payment intent properly on the server side. For instance, in our example app, we're doing:

```
const paymentIntent = await stripe.paymentIntents.create({
    amount: 5099,
    currency: 'eur',
    customer: customer.id,
    shipping: {
      name: 'Jane Doe',
      address: {
        state: 'Texas',
        city: 'Houston',
        line1: '1459  Circle Drive',
        postal_code: '77063',
        country: 'US',
      },
    },
    payment_method_types: [
      'card',
      'sepa_debit',
    ],
  });
  ```

**Comment by charliecruzan-stripe** [comment] 2022-08-09 16:34
Closing since there's no reproducible demo, and this works in the example app. Can reopen if a demo is provided

**Closed by charliecruzan-stripe** 2022-08-09 16:34 UTC
Labels: reproduce

**Comment by ShwetaChauhan18** [comment] 2022-09-01 06:10
I am facing same issue in flutter also. This SEPA DD works in 1 time payment but when you open payment sheet for subscription then it throws same error which @mahpgnaohhnim posted.

Can you please help us??

https://github.com/flutter-stripe/flutter_stripe/issues/897

<img width="394" alt="sepaDD" src="https://user-images.githubusercontent.com/34509457/187843997-06777c19-0520-422d-87c5-d80a2455faea.png">

**Comment by charliecruzan-stripe** [comment] 2022-09-02 07:49
@ShwetaChauhan18 SEPA debit isn't supported on Payment Sheet with setup intents yet: https://github.com/stripe/stripe-android/blob/master/CHANGELOG.md#1810---2021-10-18

**Comment by ShwetaChauhan18** [comment] 2022-09-02 09:38
But it should work in PaymentIntent right??

https://github.com/flutter-stripe/flutter_stripe/issues/897#issuecomment-1233824823

**Comment by ShwetaChauhan18** [comment] 2022-09-02 10:20
@charliecruzan-stripe : I understand it will not work in setup intent. But, I tried in both way but here is my proper way. When I see in stripe dashboard, I am able to see 2 payment method in incomplete invoice and able to do payment from there using SEPA DD.

1. Create subscription in server side

```
async createSubscription(payload: CreateSubscriptionDto): Promise<{
    data: Stripe.Response<Stripe.Subscription> | null;
    error: Stripe.Errors | null;
  }> {
    try {
      const {
        customerId,
        priceId,
        coupon = null,
        trial_end = null,
        metadata,
        default_payment_method = null,
      } = payload;
      let payment_behaviour = payload.payment_behaviour;
      const PAYMENT_BEHAVIOUR = Object.values(paymentBehaviour);
      if (
        !payment_behaviour ||
        !PAYMENT_BEHAVIOUR.includes(payment_behaviour)
      ) {
        payment_behaviour = paymentBehaviour.DEFAULT_INCOMPLETE;
      }
      let paymentMethodType: Stripe.Emptyable<
        Stripe.SubscriptionCreateParams.PaymentSettings.PaymentMethodType[]
      > = ['card'];
      const priceInfo: Stripe.Response<Stripe.Price> =
        await this.stripeClient.prices.retrieve(priceId);
      if (priceInfo?.currency === 'eur') {
        paymentMethodType = ['card', 'sepa_debit'];
      }
      const createSubscription: Stripe.SubscriptionCreateParams = {
        customer: customerId,
        items: [{ price: priceId }],
        coupon,
        payment_behavior: payment_behaviour,
        expand: ['latest_invoice.payment_intent', 'pending_setup_intent'],
        metadata,
        payment_settings: {
          payment_method_types: paymentMethodType,
        },
      };
      if (trial_end) {
        createSubscription.trial_end = trial_end;
        createSubscription.payment_behavior = paymentBehaviour.ALLOW_INCOMPLETE;
      }
      if (default_payment_method) {
        createSubscription.default_payment_method = default_payment_method;
      }
      const subscriptionInfo: Stripe.Response<Stripe.Subscription> =
        await this.stripeClient.subscriptions.create(createSubscription);
      if (!subscriptionInfo) {
        return { data: null, error: null };
      }
      return { data: subscriptionInfo, error: null };
    } catch (error) {
      return { data: null, error: error };
    }
  }
```

2. In response I will get ClientSecret

`{subscriptionId: sub_1Ld6I1GVrxoPH8K0AH6Alnuc, customerId: cus_MJcqkLF2BE29I1, payment_intent: {clientSecret: pi_3Ld6I2GVrxoPH8K02ceAEvai_secret_TFTa0uL1BJMk8G8ReTxlyhHti}, pending_setup_intent: {clientSecret: null}, prices: {price: 1000, currency: eur}, subscriptionStatus: incomplete}}`

3. Using this ClientSecret open PaymentSheet. 

<img width="387" alt="stripe" src="https://user-images.githubusercontent.com/34509457/188118359-dd364458-8707-44e5-aa02-5ad8aa552807.png">

4. I can share stripe dashboard response for subscription in which payment method was added.

```
"payment_settings": {
      "payment_method_options": null,
      "payment_method_types": [
        "card",
        "sepa_debit"
      ],
      "save_default_payment_method": "off"
    },
```

**Comment by ShwetaChauhan18** [comment] 2022-09-05 16:39
@charliecruzan-stripe : Can you please check this reply?? It would be really help us if you check and confirm.


https://github.com/flutter-stripe/flutter_stripe/issues/897#issuecomment-1236752123
