### ISSUE TITLE
Getting error after installing the stripe package.

### ISSUE THREAD

**Issue by trishaleelakhariya** [stripe/stripe-react-native#722] opened 2021-11-16 11:35 UTC
After installing the **stripe** package in the project, it gives the error as in the below image.

![Screenshot 2021-11-16 at 4 56 00 PM](https://user-images.githubusercontent.com/76681105/141978182-b6d9f645-a82e-4fe0-b2c0-50898beba3bb.png)

**Steps to reproduce the behavior:**

Install the stripe module with the below command.
yarn add @stripe/stripe-react-native
or
npm install @stripe/stripe-react-native

cd ios && pod install && cd ..

Open the xcworkspace file in XCode and run the project.

**Expected behavior**
Run the project after resolving the errors.

OS: _macOS Monterey_
Development target _iOS 11.0_

**Comment by emernuness** [comment] 2022-01-04 20:40
Same issue for me

**Comment by stivensevolution** [comment] 2022-01-07 05:12
> Same issue for me
i am also having same issue.
Hi, @emernuness have you found any solution yet ?

**Comment by sudhirwork** [comment] 2022-01-07 11:19
![image](https://user-images.githubusercontent.com/64832452/148536496-4e096c41-f6e2-4bdc-913a-8019b0615243.png)
Check this image, it will solve your issue.

**Comment by charliecruzan-stripe** [comment] 2022-02-11 20:44
duplicate of https://github.com/stripe/stripe-react-native/issues/721

**Closed by charliecruzan-stripe** 2022-02-11 20:44 UTC
