### ISSUE TITLE
Expo Managed Workflow Crashes On Startup for iOS.

### ISSUE THREAD

**Issue by widjesh** [stripe/stripe-react-native#904] opened 2022-04-25 01:39 UTC
**Description**
Installed "@stripe/stripe-react-native": "0.2.3" through expo install @stripe/stripe-react-native.
The problem is that once I eas build my expo app for simulator, the application crashes on load.
I have a managed workflow expo application where i am running a react native application.

**To Reproduce**
1. Create react native app with expo
2. Import the StripeProvider and add the publishableKey
3. run `eas build -p ios --profile preview` with correct simulator configuration as mentioned below
4. drag and drop the file to a simulator

eas.json file:
`{
  "cli": {
    "version": ">= 0.51.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "ios": {
        "simulator": true
      },
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
`

**Expected behavior**
The screen will crash on load

**Smartphone **
 - Device: iPhone 12 Simulator --> Same thing happens if pushed to testflight

**Additional context**
I have been trying to write to stripe customer service as well as calling in to them, but all they tell me is to wait. 
I have a case open for more then 2,5 weeks and I am in production already using stripe.js, but most of my payments are failing in there.

**Comment by charliecruzan-stripe** [comment] 2022-04-25 13:29
What's in the crash log? Your application could be crashing for many different reasons so I'm not sure if it's Stripe.

**Comment by widjesh** [comment] 2022-04-25 13:31
If i comment out stripeprovider and the other components, i dont see the app crashing.

Crash log:
Date/Time:           2022-04-25 08:20:24.5211 -0400
Launch Time:         2022-04-25 08:20:23.3591 -0400
OS Version:          macOS 12.3.1 (21E258)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  1

Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Requiring module "1152", which threw an exception: Invariant Violation: Native module cannot be null.', reason: 'Unhandled JS Exception: Error: Requiring module "1152", which threw an exception: Invariant Violation: Native module cannot be null., stack:

As you can see there is a JS exception that remains unhandled.

**Comment by charliecruzan-stripe** [comment] 2022-04-25 13:52
`RCTFatalException: Unhandled JS Exception: Error: Requiring module "1152", which threw an exception: Invariant Violation: Native module cannot be null`

Sounds to me like it's trying to find the Stripe native module and it's not there. can you try `expo run:ios`?

**Comment by charliecruzan-stripe** [comment] 2022-04-25 14:06
> Something went wrong installing JavaScript dependencies, check your yarn logfile or run yarn install again manually.

yeah something is wrong in the project configuration. maybe try removing yarn.lock and nuking node_modules and reinstalling everything

**Comment by widjesh** [comment] 2022-04-25 14:08
Yes i did remove everything and did reinstall already. I have been spending over 2 full days on this issue, but still no luck.
Not sure if this is something related to expo and stripe or just with my project and EAS build.
Do you have any suggestion ?

**Comment by charliecruzan-stripe** [comment] 2022-04-25 14:13
I would try it in a brand new blank project

**Comment by charliecruzan-stripe** [comment] 2022-04-25 14:20
Okay, then please share a github repo that is just a plain react native project + react native stripe that i can use to reproduce it

**Comment by charliecruzan-stripe** [comment] 2022-04-25 16:34
that project has [a lot of dependencies](https://github.com/widjesh/react-native-stripe/blob/master/package.json#L11-L85), can you try this with a blank project?

**Comment by widjesh** [comment] 2022-04-25 17:35
I have updated the repository with only the dependencies i need for that one screen, still the same issue exists.

**Comment by charliecruzan-stripe** [comment] 2022-04-25 18:40
cloned that repo and ran `expo run:ios` with the newest expo-cli, and it's working for me

**Comment by widjesh** [comment] 2022-04-25 18:43
Can you try to build with eas ? Because for stripe we need to use eas build inorder have the dependency included. 
Becuase the app wont open on a simulator. it crashes right away after that simulator build command with eas

**Comment by charliecruzan-stripe** [comment] 2022-04-25 18:47
Can you try to address the issue with your project [mentioned here](https://github.com/stripe/stripe-react-native/issues/904#issuecomment-1108612032)? Debugging this with a local build is much easier than running builds through eas. It should function the same when you use `expo run:ios`

**Comment by widjesh** [comment] 2022-04-25 18:57
This is the complete stack trace when i run expo run:ios with 5.0.4 version of expo-cli

`⚠️  Pods/boost-for-react-native: iOS@8.0 deployment version mismatch, expected >= 9.0 <= 14.4.99
    Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the reactnativestripe editor. (in target 'reactnativestripe' from project 'reactnativestripe')

› 3 error(s), and 2 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.`

**Comment by charliecruzan-stripe** [comment] 2022-04-25 18:58
I dont think that stack trace is complete. It only shows 1 warning, but 3 errors occurred.

**Comment by widjesh** [comment] 2022-04-25 18:59
Yea you are right

This is what i could get more:

  (node_modules/expo-modules-core/ios/Swift/Views/ConcreteViewProp.swift:42:55)

  40 |     }
  41 |     guard let value = try propType.cast(value) as? PropType else {
> 42 |       throw Conversions.CastingError<PropType>(value: value)
     |                                                       ^ variable declared in 'guard' condition is not usable in its body
  43 |     }
  44 |     setter(view, value)
  45 |   }


❌  (node_modules/expo-modules-core/ios/Swift/Arguments/Types/EnumArgumentType.swift:46:58)

  44 |   static func create<ArgType>(fromRawValue rawValue: ArgType) throws -> Self {
  45 |     guard let rawValue = rawValue as? RawValue else {
> 46 |       throw EnumCastingError(type: RawValue.self, value: rawValue)
     |                                                          ^ variable declared in 'guard' condition is not usable in its body
  47 |     }
  48 |     guard let enumCase = Self.init(rawValue: rawValue) else {
  49 |       throw EnumNoSuchValueError(type: Self.self, value: rawValue)


❌  (node_modules/expo-modules-core/ios/Swift/Modules/ModuleDefinitionComponents.swift:212:27)

  210 |    Creates the view manager definition that scopes other view-related definitions.
  211 |    */
> 212 |   public func viewManager(@ViewManagerDefinitionBuilder _ closure: @escaping () -> ViewManagerDefinition) -> AnyDefinition {
      |                           ^ unknown attribute 'ViewManagerDefinitionBuilder'
  213 |     return closure()
  214 |   }
  215 |

**Comment by charliecruzan-stripe** [comment] 2022-04-25 19:00
looks like an issue with expo

**Comment by widjesh** [comment] 2022-04-25 19:00
im using sdk 44, what did you use?

**Comment by charliecruzan-stripe** [comment] 2022-04-25 19:09
your linked project, i didn't change anything

**Comment by widjesh** [comment] 2022-04-25 19:10
Thats weird, any suggestions ?

**Comment by charliecruzan-stripe** [comment] 2022-04-25 19:11
Unfortunately no, this looks like an issue with your local project, not a bug with stripe-react-native 😞

**Comment by widjesh** [comment] 2022-04-25 19:12
well, the same issue exists when running through eas buid and running the app from test flight. So not pretty sure

**Comment by charliecruzan-stripe** [comment] 2022-04-25 19:14
My recommendation is to debug and fix the failures that you listed above, pointing at `expo-modules-core`, and get a local build working with `expo run:ios`

**Comment by widjesh** [comment] 2022-04-25 19:15
ok thanks

**Comment by charliecruzan-stripe** [comment] 2022-04-28 22:29
Closing this for now since it doesn't seem like an issue with Stripe (stack trace points to expo-modules-core), but will reopen if a reproducible demo is provided

**Closed by charliecruzan-stripe** 2022-04-28 22:29 UTC
Labels: invalid

**Comment by kesylo** [comment] 2022-06-02 22:35
I have the same issue @charliecruzan-stripe 
During EAS build, it fails during Fastlane step: **Entitlements file defines the value "com.apple.developer.in-app-payments" which is not registered for profile**
I don't have this issue on android. Also using Expo SDK 44 and @stripe/stripe-react-native: "0.2.3"

`$ set -o pipefail && xcodebuild -workspace ./Sendylostg.xcworkspace -scheme Sendylostg -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/expo/Library/Developer/Xcode/Archives/2022-06-02/Sendylostg\ 2022-06-02\ 15.24.43.xcarchive archive | tee /Users/expo/workingdir/logs/Sendylostg-Sendylostg.log > /dev/null
❌  Sendylostg/Sendylostg: Provisioning Profile "*[expo] com.sendylo.sendylostg AppStore 2021-10-29T12:24:29.627Z" does not support the Apple Pay capability.

❌  error: Provisioning profile "*[expo] com.sendylo.sendylostg AppStore 2021-10-29T12:24:29.627Z" doesn't support the merchant.com.sendylo.sendylostg Merchant ID. (in target 'Sendylostg' from project 'Sendylostg')

❌  Sendylostg/Sendylostg: Entitlements file defines the value "com.apple.developer.in-app-payments" which is not registered for profile "*[expo] com.sendylo.sendylostg AppStore 2021-10-29T12:24:29.627Z".
▸ ** ARCHIVE FAILED **
** ARCHIVE FAILED **
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.185.1                 |
| sdk         | iPhoneOS15.0.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[stderr] 
[!] Error building the application - see the log above
Error: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.`

**Comment by brunolcarlos** [comment] 2022-06-27 01:37
I have the same problem with SDK 43, the Android works perfect but the IOS show the error when I send to EAS 

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace ./xxxxxxxxx.xcworkspace -scheme xxxxxxxxx -configuration Release -destination generic/platform=iOS -archivePath "/Users/expo/Library/Developer/Xcode/Archives/2022-06-26/BomPerfil 2022-06-26 18.34.05.xcarchive" archive
User defaults from command line:
    IDEArchivePathOverride = /Users/expo/Library/Developer/Xcode/Archives/2022-06-26/xxxxxxxxx 2022-06-26 18.34.05.xcarchive
    IDEPackageSupportUseBuiltinSCM = YES
note: Using new build system
note: Planning
Analyze workspace
Create build description
Build description signature: 6d69dbd30ce0b142fc03c1dc347a6b88
Build description path: /Users/expo/Library/Developer/Xcode/DerivedData/BomPerfil-dttosrnzwvrgfdaaiqzozgmirrst/Build/Intermediates.noindex/ArchiveIntermediates/BomPerfil/IntermediateBuildFilesPath/XCBuildData/6d69dbd30ce0b142fc03c1dc347a6b88-desc.xcbuild
note: Build preparation complete
note: Building targets in parallel
/Users/expo/workingdir/build/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'boost-for-react-native' from project 'Pods')
error: Provisioning profile "xxxxxxxxx" has app ID "com.xxxxxxxxx.ios", which does not match the bundle ID "com.xxxxxxxxx.ios.OneSignalNotificationServiceExtension". (in target 'OneSignalNotificationServiceExtension' from project 'xxxxxxxxx')

**Comment by brunolcarlos** [comment] 2022-06-27 16:43
> @brunolcarlos your error message doesn't point to Stripe:
> 
> > error: Provisioning profile "xxxxxxxxx" has app ID "com.xxxxxxxxx.ios", which does not match the bundle ID "com.xxxxxxxxx.ios.OneSignalNotificationServiceExtension". (in target 'OneSignalNotificationServiceExtension' from project 'xxxxxxxxx')
> 

No but the scenario looks like the same error.

**Comment by charliecruzan-stripe** [comment] 2022-06-27 17:11
Not sure what you mean by that 🤔  the errors in the logs @widjesh shared indicate maybe an unexpected swift or xcode version, whereas your error indicates that your credentials, specifically your provisioning profile for your Notification Service Extension, are invalid
