### ISSUE TITLE
Payment sheet cut off on Google Pixel 6

### ISSUE THREAD

**Issue by jsindos** [stripe/stripe-react-native#1099] opened 2022-08-23 05:37 UTC
**Describe the bug**
When opening the payment sheet with `customFlow: true` on Android, the bottom of the payment sheet is cut off.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8110172/186077741-793705eb-837f-4dac-8cae-f775a0831b34.png" height="600" />

**Smartphone**
 - Device: Google Pixel 6
 - OS: Android 12

**Additional context**
Running `@stripe/stripe-react-native: 0.13.1`, going to try updating to the latest version to see if this fixes the issue, however I didn't see any of mention of this issue in the changelogs.

I've tested the same version on iOS (iPhone 7), and the issue doesn't exist.

**Comment by charliecruzan-stripe** [comment] 2022-08-24 19:23
> Running @stripe/stripe-react-native: 0.13.1, going to try updating to the latest version to see if this fixes the issue, however I didn't see any of mention of this issue in the changelogs.

Yeah I don't think that there were any recent changes on Android that would affect this, but lmk if you see the same behavior on 0.18.1

**Comment by jsindos** [comment] 2022-08-25 03:25
I've also found this issue to occur generally as I'm building my app, all of my pages are overflowing off the screen on the bottom. I'll test the same code on another Android device and see if it persists.

**Comment by charliecruzan-stripe** [comment] 2022-08-25 20:39
> all of my pages are overflowing off the screen on the bottom

Yeah this seems like it's not an issue with the `stripe-react-native` library then

**Comment by charliecruzan-stripe** [comment] 2022-08-29 21:38
Hi @jsindos , if you're seeing this behavior across multiple screens (not just with the Payment Sheet), I think it's best to close this issue as it's probably not caused by Stripe

**Closed** 2022-09-02 09:52 UTC

**Comment by jsindos** [comment] 2022-10-27 04:18
So I installed 0.19.0 and it fixed the problem! For anyone reading this, note this requires `compileSdkVersion` to be at least 33.
