### ISSUE TITLE
Fatal Exception: com.stripe.android.exception.CardException Your card was declined.

### ISSUE THREAD

**Issue by DodoSpringLove** [stripe/stripe-react-native#1003] opened 2022-06-21 06:25 UTC
**Describe the bug**
Fatal Exception: com.stripe.android.exception.CardException
Your card was declined.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Device
Brand:Xiaomi
Model:Redmi Note 8
Orientation: Portrait
RAM free: 1.02 GB
Disk free: 27.26 GB
Operating System
Version:Android 11
Orientation: Portrait
Rooted:No
Crash
Date:Jun 21, 2022, 1:04:00 AM
"@stripe/stripe-react-native": "0.2.1",

**Additional context**
Fatal Exception: com.stripe.android.exception.CardException: Your card was declined.
       at com.stripe.android.networking.StripeApiRepository.handleApiError(StripeApiRepository.kt:1110)
       at com.stripe.android.networking.StripeApiRepository.makeApiRequest$payments_core_release(StripeApiRepository.kt:1158)
       at com.stripe.android.networking.StripeApiRepository$makeApiRequest$1.invokeSuspend(StripeApiRepository.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by charliecruzan-stripe** [comment] 2022-06-22 17:25
Closing since we need the template to be fully filled out in order to help with bug reports. Also, it looks like you're using a combo of React and React Native libraries, and your version of stripe-react-native is pretty old. Happy to help if you can provide a reproducible demo, though

**Closed by charliecruzan-stripe** 2022-06-22 17:25 UTC
