### ISSUE TITLE
PaymentSheet Crashing on Android in v.0.19.0

### ISSUE THREAD

**Issue by Ace090** [stripe/stripe-react-native#1193] opened 2022-11-04 00:15 UTC
**Describe the bug**
In v0.19.0, on Android (13 and 10), presentPaymentSheet call crashes the app without any errors. After installing Sentry I see a `IllegalStateException: ViewTreeLifecycleOwner not found`

On iOS everything works perfectly.

**To Reproduce**
I'm just following this [Stripe Developers video](https://youtu.be/O6TWFuZw2uk) about [Accept a payment](https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet):

```
export default function TestPaymentScreen(props) {
	const [ready, setReady] = useState(false);
  const {initPaymentSheet, presentPaymentSheet, loading} = usePaymentSheet();

  useEffect(() => {
    initializePaymentSheet();
  }, []);

  const initializePaymentSheet = async () => {
    const {paymentIntent, ephemeralKey, customer} =
      await fetchPaymentSheetParams();

    const {error} = await initPaymentSheet({
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,
      merchantDisplayName: 'MyApp',
      allowsDelayedPaymentMethods: true,
      returnURL: 'stripe-example://stripe-redirect',
    });
    if (error) {
      Alert.alert(`Error codes: ${error.code}`, error.message);
    } else {
      setReady(true);
    }
  };

  const fetchPaymentSheetParams = async () => {
    const response = await fetch(`http://192.168.1.67:8000/checkout`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const {paymentIntent, ephemeralKey, customer} = await response.json();

    return {
      paymentIntent,
      ephemeralKey,
      customer,
    };
  };

  async function buy() {
    const {error} = await presentPaymentSheet();

    if (error) {
      Alert.alert(`Error code: ${error.code}`, error.message);
    } else {
      Alert.alert('Success', 'The payment was confirmed successfully');
      setReady(false);
    }
  }

   /* ... */
}
```
When `openPaymentSheet()` is called pressing the button, the android app crashes without any error in the Metro server console.
The Sentry dashboard shows:
```
IllegalStateException
ViewTreeLifecycleOwner not found from androidx.coordinatorlayout.widget.CoordinatorLayout{5876b97 V.E...... ......I. 0,0-0,0 #7f0800cf app:id/coordinator}
```

**Expected behavior**
Payment sheet opening

**Smartphone**
 - Device: Pixel 4 
 - OS: Android
 - Version 13

**I attach the following files:**
[android:app:build.gradle.txt](https://github.com/stripe/stripe-react-native/files/10014034/android.app.build.gradle.txt)
[android:build.gradle.txt](https://github.com/stripe/stripe-react-native/files/10014035/android.build.gradle.txt)
[package.json.txt](https://github.com/stripe/stripe-react-native/files/10014036/package.json.txt)

**Comment by victorgalvez56** [comment] 2022-11-15 16:02
That happens to me too.

**Comment by Ace090** [comment] 2022-11-16 14:15
I tried updating to 0.20.0 and also to the latest 0.21.0 released yesterday 2022-11-15 but the problem persists.

**Comment by victorgalvez56** [comment] 2022-11-16 14:21
Yesterday I updated to version 0.20.0 and the problem continues. The strange thing is that I don't get any errors. It just doesn't work.

**Comment by Ace090** [comment] 2022-11-16 14:28
Yes, me too the app crashes without any error when presentPaymentSheet() is called.

**Comment by MohNaweed** [comment] 2022-11-23 15:44
Does anyone find the solution ????

**Comment by Ace090** [comment] 2022-11-25 08:43
> Does anyone find the solution ????
unfortunately not

**Comment by KOSIDOCS** [comment] 2022-12-05 15:49
Having Same issue here too. The payment sheet is not opening on Android.

**Comment by MohNaweed** [comment] 2022-12-05 16:02
> Having Same issue here too. The payment sheet is not opening on Android.

I just added the merchantDisplayName: 'anything' in initialPaymentSheet object and it solved it for me

**Comment by Ace090** [comment] 2022-12-05 16:08
> > Having Same issue here too. The payment sheet is not opening on Android.
> 
> I just added the merchantDisplayName: 'anything' in initialPaymentSheet object and it solved it for me

Not for me. Even adding `merchantDisplayName: 'anything'` to `initPaymentSheet` the app keeps crashing on Android

**Comment by here4learning** [comment] 2022-12-05 16:54
@Ace090 I am getting "did not call through to super.onCreate()" . I have added merchantDisplayName: 'anything' , but still getting the eroor. Any solution?

**Comment by KOSIDOCS** [comment] 2022-12-05 16:56
> > > Having Same issue here too. The payment sheet is not opening on Android.
> > 
> > 
> > I just added the merchantDisplayName: 'anything' in initialPaymentSheet object and it solved it for me
> 
> Not for me. Even adding `merchantDisplayName: 'anything'` to `initPaymentSheet` the app keeps crashing on Android

Guy's I was able to fix mine, So mine was caused by using using custom font in `appearance: customAppearance,` fontfamily. make sure to add your font in here `android/app/src/main/res/font`

**Comment by Ace090** [comment] 2022-12-05 17:29
> 

I am not using the `appearance` prop in `initPaymentSheet`. Even using it, unfortunately for me, the app keeps crashing without any errors on Android.

**Comment by KOSIDOCS** [comment] 2022-12-05 17:36
@Ace090 Oh that's strange. Send me a google meet link and we can look into it together. Mine was fixed by just doing that.

**Comment by here4learning** [comment] 2022-12-05 17:48
@Ace090 same for me. Please let me know, if there is any solution.

**Comment by charliecruzan-stripe** [comment] 2022-12-06 00:13
Hi, I haven't been able to reproduce this so far. Can someone who is able to trigger this crash please run it while running `adb logcat` and find the fatal exception there and share it here? thanks!

**Comment by Ace090** [comment] 2022-12-06 09:50
> Hi, I haven't been able to reproduce this so far. Can someone who is able to trigger this crash please run it while running `adb logcat` and find the fatal exception there and share it here? thanks!

Hi @charliecruzan-stripe , running `adb logcat` I have this fatal exception when I call `presentPaymentSheet`

```
12-06 10:39:58.984 11777 11777 D AndroidRuntime: Shutting down VM
12-06 10:39:58.987 11777 11777 E AndroidRuntime: FATAL EXCEPTION: main
12-06 10:39:58.987 11777 11777 E AndroidRuntime: Process: com.indidev, PID: 11777
12-06 10:39:58.987 11777 11777 E AndroidRuntime: java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from androidx.coordinatorlayout.widget.CoordinatorLayout{9409402 V.E...... ......I. 0,0-0,0 #7f0800cf app:id/coordinator}
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:349)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:324)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:299)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:242)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:249)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.onAttachedToWindow(ComposeView.android.kt:281)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:19587)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2034)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1727)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7612)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:852)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:787)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:359)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7418)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-06 10:39:58.987 11777 11777 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
12-06 10:39:58.994  1789  4879 E InputDispatcher: Window handle drag has no registered input channel
12-06 10:39:59.021  1789  4879 D ActivityManager: New dropbox entry: com.indidev, data_app_crash, 6317ce3b-534f-48ec-bce4-812882900499
12-06 10:39:59.022  1789  4879 W ActivityTaskManager:   Force finishing activity com.indidev/com.stripe.android.paymentsheet.PaymentSheetActivity
12-06 10:39:58.994  1789  4879 I chatty  : uid=1000(system) Binder:1789_15 identical 19 lines
12-06 10:39:58.994  1789  4879 E InputDispatcher: Window handle drag has no registered input channel
12-06 10:39:59.022  1789  4879 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
12-06 10:39:59.023  1789  4879 W ActivityTaskManager:   Force finishing activity com.indidev/.MainActivity
12-06 10:39:59.024  1789 12462 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-06 10:39:59.027  1789  4884 E InputDispatcher: Window handle drag has no registered input channel
```

**Comment by charliecruzan-stripe** [comment] 2022-12-06 23:01
@Ace090 why do you have `implementation(project(':stripe_stripe-react-native')) { exclude module: 'appcompat' }` in your `app/build.gradle`?

**Comment by Ace090** [comment] 2022-12-06 23:50
Thank you very much @charliecruzan-stripe  that was the problem. I had added it to the `app/build.gradle` because without it I get the error `Attempt to invoke virtual method'boolean com.facebook.react.uimanager.FabricViewStateManager.hasStateWrappper()`.
I just tried replacing it with
```
implementation ("androidx.appcompat:appcompat:1.3.1") {
    version {
        strictly '1.3.1'
    }
}
```
and everything works fine. 🙏

**Closed** 2022-12-06 23:51 UTC
Labels: reproduce

**Comment by charliecruzan-stripe** [comment] 2022-12-06 23:58
Awesome! Glad to hear it, hopefully that addresses it for the remainder of folks experiencing random payment sheet crashes in this issue. Thanks for posting here!

**Comment by ankitk-nimblechapps** [comment] 2023-02-06 08:25
I am Currently having react-native 0.68.0, stripe library version is 0.19.0, getting crashed with these error while calling initPaymentSheet method 
![Screenshot_2023-02-06-13-29-59-94_a40c374f801420dce36ea483382aa15e](https://user-
images.githubusercontent.com/77725221/216921143-c32a1efc-4dc6-4577-88a4-22bf7b4f9552.jpg)
