### ISSUE TITLE
Xcode AppDelegate.m crash when interact with CardField component in reload state

### ISSUE THREAD

**Issue by carl0shd** [stripe/stripe-react-native#303] opened 2021-06-02 03:21 UTC
**Describe the bug**
When i interact with the `CardField` component (click in the fields, filling the card number input) and when I run the command to reload the application (⌘ + r) the AppDelegate.m crashes. It only happens when i interact with the component and after, execute the reload command. If i press the R key in the RN server to reload the app, or open the debug mode and click Reload, the app doesn't crash, only happen with ⌘ + r command after interacting with the component.

I already try to run the command ⌘ + r whitout interact with the component and nothing happens, appears to be the component.

**To Reproduce**
1. Open the app with a view that have a `CardField` component rendered.
2. Interact with the `CardField` component, for example, try to fill the card number input `(insert 4242 4242)`.
3. Executes the ⌘ + r command to do a fast reload of the application.

_**PD: if the Xcode doesn't crash the first time, try again, something the bug happens at the 2nd or 3rd time. (yes, is pretty weir.)**_

**Expected behavior**
React Native should be able to completes the reload of the application without the AppDelegate.m crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/8359234/120418750-bbb05080-c326-11eb-89ee-ec71e7935dfa.png)

**Smartphone (please complete the following information):**
 - Device: Xcode Iphone 11 Simulator
 - OS: IOS 14.4
- RN version: 0.63.4

**Comment by thorsten-stripe** [comment] 2021-06-02 07:02
I'm not able to reproduce this. I'm not sure this is related to the library. How would this affect your production app?

**Comment by carl0shd** [comment] 2021-06-02 15:59
Hi, this not affect the production build but when you develops your integration with the library and if you use the ⌘ + r command to reload the app, the apps crashes. I attach a video to expand the context of how the crash works.

https://user-images.githubusercontent.com/8359234/120513153-99075180-c391-11eb-9790-6e2521a31919.mp4

**Comment by konstantinmv** [comment] 2021-06-08 10:11
This also happens to me with the introduction of `CardField` component into the app, this was not happening before that event. 
Not sure what will help you to debug this problem and find the solution.

**Comment by konstantinmv** [comment] 2021-06-10 13:26
I may have some more information on this problem.
So after building on a real device in development, I still have this issue (fortunately, it does not happen not in dev)
I have a modal, which then has the `CardField`. When dismissing this modal, the app crashes. 

The crash is logged as:
File `STPValidatedTextField.swift`
Line 88, `func updateColor`
Thread 1: EXC_BAD_ACCESS (code=1, address=0x699422490)

This happens every time I open and then close the modal. This did not happen before adding the `CardField` component, so I'm pretty positive it's the reason for the crash.
Thanks!

![image](https://user-images.githubusercontent.com/54809274/121532955-1ec57580-ca00-11eb-95f1-08552726de78.png)

**Comment by arekkubaczkowski** [comment] 2021-08-11 10:47
this is already fixed in `0.2.0v`

**Closed by arekkubaczkowski** 2021-08-11 10:47 UTC
Labels: question, need triage
