### ISSUE TITLE
Cancel presented Apple Pay

### ISSUE THREAD

**Issue by rob5408** [stripe/stripe-react-native#918] opened 2022-05-02 12:54 UTC
**Is your feature request related to a problem? Please describe.**
In my app I followed the steps [here](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ApplePayScreen.tsx) to...

1.  Present an Apple Pay screen
2. Fetch a Payment Intent from my server
3. Confirm Apple Pay

...however in development I had an issue in my payment intent endpoint and while this was communicated back to the app immediately I had to wait for the Apple Pay screen to timeout (15s?) to inform the user.

**Describe the solution you'd like**
I've read a bunch of documentation and I don't think this has been considered yet. Happiest if the solution was just to use an existing method. Now, ideally all my endpoints work as they should all the time, but I'm a belt and suspenders kinda guy. If the server throws back an error it would be nice to manually cancel the Apple Pay screen. I was thinking about something like this...

```
    const { error, paymentMethod, cancelApplePay } = await presentApplePay({ ... });
```

Where `cancelApplePay` is just a method I could call to dismiss the Apple Pay screen immediately.

**Describe alternatives you've considered**
I have thought maybe I should just get the Payment Intent first which would allow me to skip the awkward situation caused by the above where Apple Pay presents and then dismisses with an error unrelated to Apple Pay. I think this is probably best as it requires no SDK change except for maybe different guidance in the example code or documentation. I generally try not to deviate from y'alls instructions though.

I've also thought about instead of my normal flow of immediately throwing from my Payment Intent endpoint instead  providing a known invalid client secret to confirmApplePayPayment so it just fails quicker.

```
const pay = async () => {
    const { error, paymentMethod } = await presentApplePay({ ... });

    if (error) {
      Alert.alert(error.code, error.message);
    } else {
      let clientSecret = "INVALID"
      try {
         clientSecret = await fetchPaymentIntentClientSecret();
      } catch (error) {
      }

      const { error: confirmApplePayError } = await confirmApplePayPayment(
        clientSecret
      );

      if (confirmApplePayError) {
        Alert.alert(confirmApplePayError.code, confirmApplePayError.message);
      } else {
        Alert.alert('Success', 'The payment was confirmed successfully!');
      }
    }
  };

```

**Additional context**
None.

**Comment by charliecruzan-stripe** [comment] 2022-05-04 19:48
hi! going to close this as a duplicate of https://github.com/stripe/stripe-react-native/issues/447, but I really appreciate the thorough explanation, and we'll take this into account when building this feature 😄

**Closed by charliecruzan-stripe** 2022-05-04 19:48 UTC
