### ISSUE TITLE
Exception in native call from JS createTokenFromBankAccount

### ISSUE THREAD

**Issue by ravi-poonia** [stripe/stripe-react-native#1072] opened 2022-08-04 08:03 UTC
**Describe the bug**
Getting error while trying to create token for bank account

<img width="331" alt="Screenshot 2022-08-04 at 1 31 59 PM" src="https://user-images.githubusercontent.com/61002302/182795848-24341bcb-365c-41cc-b431-9edc7befa32a.png">

**Comment by charliecruzan-stripe** [comment] 2022-08-04 17:00
Closing this since there's not enough information to go off of. If you can edit the original issue and include your version of `stripe-react-native` and sample code to reproduce the exception, I'm happy to take a look! 

Here's our example screen on creating tokens- https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/CreateTokenScreen.tsx - that might help to debug here.

**Closed by charliecruzan-stripe** 2022-08-04 17:00 UTC
