### ISSUE TITLE
Getting length=0; index=0 as an error from presentGooglePay

### ISSUE THREAD

**Issue by leudy015** [stripe/stripe-react-native#874] opened 2022-03-31 11:28 UTC
When starting a payment with google pay through stripe I get this error attached photo

my code

export const payGooglePay = async (
  presentGooglePay,
  setInitialized,
  amount,
  currency,
  setLoading,
  customer,
) => {
  setLoading(true);
  // 2. Fetch payment intent client secret
  const paymentIntent = await fetchPaymentIntentClientSecret(
    amount,
    currency,
    customer,
  );

  const client_secret = paymentIntent.client_secret;
  // 3. Open Google Pay sheet and proceed a payment
  const {error} = await presentGooglePay({
    client_secret,
    forSetupIntent: false,
  });

  if (error) {
    Alert.alert(error.code, `${JSON.stringify(error)}`);
    return {
      succeed: false,
      paymentIntent: null,
    };
  } else {
    setInitialized(false);
    return {
      succeed: true,
      paymentIntent: paymentIntent,
    };
  }
};
![Screenshot_20220331-131533_Rentyt](https://user-images.githubusercontent.com/49622506/161045026-5c82cf84-4233-4b0c-bd1c-fed46b0f5d94.jpg)

**Comment by charliecruzan-stripe** [comment] 2022-03-31 13:08
@leudy015 this is the same as https://github.com/stripe/stripe-react-native/issues/633#issuecomment-1084448582, have you tried the fixes there? It ended up being a server side error. As I said in that issue, please provide a way for us to reproduce the problem (both client and server code)

**Comment by leudy015** [comment] 2022-03-31 14:27
This is my server code

routerStripe.post("/payment-card", async (req, res) => {
  const { payment_method, customers, amount, currency } = req.body;
  const total = amount.toFixed(0);
  try {
    const paymentIntent = await Stripe.paymentIntents.create({
      payment_method: payment_method,
      amount: total,
      currency: currency ? currency : "USD",
      customer: customers,
      confirmation_method: "automatic",
      confirm: true,
    });
    if (paymentIntent.status === "succeeded") {
      res.status(200).json(paymentIntent).end();
    } else if (paymentIntent.status === "canceled") {
      res.status(400).json(paymentIntent).end();
    } else if (paymentIntent.status === "requires_action") {
      res.status(200).json(paymentIntent).end();
    } else {
      res.status(400).json(paymentIntent).end();
    }
  } catch (err) {
    console.log("Error code is: ", err);
    const paymentIntentRetrieved = await Stripe.paymentIntents.retrieve(
      //@ts-ignore
      err.raw.payment_intent.id
    );
    console.log("PI retrieved: ", paymentIntentRetrieved.id);
    res.status(400).json(paymentIntentRetrieved).end();
  }
});

**Comment by leudy015** [comment] 2022-03-31 14:31
these are the parameters for 

{
  amount: 11600,
  currency: 'usd',
  customer: 'cus_KjWHUAOx0rUAf1',
  payment_method_options: { card: { request_three_d_secure: 'automatic' } },
  payment_method_types: []
}

Stripe.paymentIntent.create(params)

**Comment by charliecruzan-stripe** [comment] 2022-03-31 14:35
your server expects `customers` when you're sending it `customer`

**Comment by leudy015** [comment] 2022-03-31 14:39
I have passed customers and I get this error, what should I pass in payment_method?


StripeInvalidRequestError: Received unknown parameter: customers. Did you mean customer?
    at Function.generate (/Users/leudy/Documents/rentyt/server/node_modules/stripe/lib/Error.js:40:16)
    at res.toJSON.then.StripeAPIError.message (/Users/leudy/Documents/rentyt/server/node_modules/stripe/lib/StripeResource.js:220:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'parameter_unknown',
    doc_url: 'https://stripe.com/docs/error-codes/parameter-unknown',
    message: 'Received unknown parameter: customers. Did you mean customer?',
    param: 'customers',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Thu, 31 Mar 2022 14:38:17 GMT',
      'content-type': 'application/json',
      'content-length': '268',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'idempotency-key': 'ea534aa4-69d4-427a-9f16-cf22d6e5969f',
      'original-request': 'req_nd5HEXLPhZG7Mj',
      'request-id': 'req_nd5HEXLPhZG7Mj',
      'stripe-version': '2020-08-27',
      'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
    },
    statusCode: 400,
    requestId: 'req_nd5HEXLPhZG7Mj'
  },
  rawType: 'invalid_request_error',
  code: 'parameter_unknown',
  doc_url: 'https://stripe.com/docs/error-codes/parameter-unknown',
  param: 'customers',
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Thu, 31 Mar 2022 14:38:17 GMT',
    'content-type': 'application/json',
    'content-length': '268',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'idempotency-key': 'ea534aa4-69d4-427a-9f16-cf22d6e5969f',
    'original-request': 'req_nd5HEXLPhZG7Mj',
    'request-id': 'req_nd5HEXLPhZG7Mj',
    'stripe-version': '2020-08-27',
    'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
  },
  requestId: 'req_nd5HEXLPhZG7Mj',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  payment_method_type: undefined,
  setup_intent: undefined,
  source: undefined
}

**Comment by charliecruzan-stripe** [comment] 2022-03-31 14:41
Please share a link to minimal Github repo (as little code as possible) that reproduces this, I think that debugging by going back and forth in this github thread isn't very effective 😅

**Comment by leudy015** [comment] 2022-03-31 14:59
I understand here I leave you a link for my server code thanks 😅

https://github.com/leudy015/rentyt/blob/main/index.ts

**Comment by leudy015** [comment] 2022-03-31 22:07
I had updated to version 0.5.0 and before I made the call in this way

const {error} = await presentGooglePay({
    clientSecret,
    forSetupIntent: false,
  });

but i fixed it by updating to this way

const {error} = await presentGooglePay({
    clientSecret: clientSecret,
    forSetupIntent: false,
  });

**Comment by charliecruzan-stripe** [comment] 2022-04-07 18:40
Those two function calls are identical, but glad it got fixed anyways 😅 

This `length=0; index=0` error message ususally indicates an issue in creating the payment intent on the server, or an issue with the `clientSecret` value you're passing. 

Closing this since it's fixed, but let me know if im misunderstanding your last comment, please!

**Closed by charliecruzan-stripe** 2022-04-07 18:40 UTC
