### ISSUE TITLE
handleNextAction returns "The PaymentIntent requires a PaymentMethod or Source to be attached before using STPPaymentHandler."

### ISSUE THREAD

**Issue by dmtar** [stripe/stripe-react-native#1000] opened 2022-06-17 12:57 UTC
**Describe the bug**
I'm creating a payment intent on the server with confirm = true, which obviously fails with 3ds required as I'm using the test card ending in 3220, when I try to use handleNextAction on the client to get the 3ds challenge screen I'm getting the "The PaymentIntent requires a PaymentMethod or Source to be attached before using STPPaymentHandler."

I'm following the steps in this guide https://stripe.com/docs/payments/accept-a-payment-synchronously?platform=react-native

**To Reproduce**
1. Create a payment intent with confirm = true server to server which will fail
2. Make sure the payment intent is with error code = authentication_required in the stripe test dashboard
3. Get the payment intent secret and try to call handleNextAction with it
4. The promise resolves with the error "The PaymentIntent requires a PaymentMethod or Source to be attached before using STPPaymentHandler."

**Expected behavior**
I'm expecting to get the 3ds challenge screen on the client and when it's finished correctly to get the payment intent result

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 15.5

**Comment by dmtar** [comment] 2022-06-20 05:33
On android, the error is "Your card was declined. This transaction requires authentication." and I'm not redirected to the 3ds challenge, no matter how I create the payment intent with or without `use_stripe_sdk` flag. The payment intent is created with `confirmation_method  = manual` as I want to confirm the payments only on the server

**Comment by dmtar** [comment] 2022-07-07 11:51
@charliecruzan-stripe any update on this? thanks

**Comment by charliecruzan-stripe** [comment] 2022-07-07 20:13
hm, I'm not able to reproduce this myself. @dmtar these are my steps:

1. create payment method:
```
// while cardfield is rendered
const { paymentMethod, error } = await createPaymentMethod({
      paymentMethodType: 'Card',
      paymentMethodData: { billingDetails },
    });
```
2. call endpoint that contains:
```
const params: Stripe.PaymentIntentCreateParams = {
          amount: orderAmount,
          confirm: true,
          confirmation_method: 'manual',
          currency: currency,
          payment_method: paymentMethodId,
          use_stripe_sdk: useStripeSdk,
        };
        const intent = await stripe.paymentIntents.create(params);
```

3. call handleNextAction on that new intent:

```
const { error: nextActionError, paymentIntent } = await handleNextAction(
        clientSecret // get this from the endpoint in step 2
      );
```

The problem could be you're not using `useStripeSdk`, but that would result in a different error message.

**Comment by talaikis** [comment] 2022-07-16 08:23
Maybe this will help: `stripe.paymentMethods.attach(paymentmethodId, { customer: customer.id })`

**Comment by charliecruzan-stripe** [comment] 2022-07-19 21:52
Going to close this issue for now since we haven't gotten a response yet, but happy to reopen if a repro can be provided!

**Closed by charliecruzan-stripe** 2022-07-19 21:52 UTC
Labels: reproduce

**Comment by hiteshlimbanidev** [comment] 2023-07-05 11:21
const paymentIntent = await stripe.paymentIntents.confirm(
                  clientsecret,
                  {
                    use_stripe_sdk: true,
                    key:sp_key,
                    expected_payment_method_type: "card",
                    client_secret:clientsecret
                      ,
                  }
                );
                
                after this not didn't open 3d secure card authentication API, can you please help
