### ISSUE TITLE
initGooglePay doesn't resolve upon first load

### ISSUE THREAD

**Issue by bill-pairaktaridis** [stripe/stripe-react-native#731] opened 2021-11-22 11:30 UTC
**Describe the bug**
Trying to implement Google Pay, I'm noticing that even using the exact code in https://github.com/stripe/stripe-react-native/blob/master/docs/GooglePay.md doesn't work properly

```javascript
	useEffect(() => {
		const initialize = async () => {
			const { error } = await initGooglePay({
				testEnv: true,
				merchantName: intl.formatMessage(messages.nativePayRequestCompanyLabel),
				countryCode: countryIsoCode,
				billingAddressConfig: {
					format: "FULL",
					isPhoneNumberRequired: true,
					isRequired: false,
				},
				existingPaymentMethodRequired: false,
				isEmailRequired: true,
			});

			console.log("initialize");

			if (error) {
				console.tronIfAvailable.log(error);
				return;
			}
			setGooglePayInitialized(true);
		};
		initialize();
	}, [countryIsoCode, initGooglePay, intl]);
```

If I leave and re-enter the screen that includes that code, then it resolves properly

**Expected behavior**
It should resolve every time

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T with Google Pay set up
 - OS: Android 11

**Comment by bill-pairaktaridis** [comment] 2021-11-26 11:21
I was able to resolve it on my end. It seemed to be a problem with my setup.

**Comment by charliecruzan-stripe** [comment] 2022-02-11 22:10
hi @bill-pairaktaridis , I tested this using the example from the docs:

```js
React.useEffect(() => {
    async function initialize() {
      const { error } = await initGooglePay({
        testEnv: true,
        merchantName: 'Test',
        countryCode: 'US',
        billingAddressConfig: {
          format: 'FULL',
          isPhoneNumberRequired: true,
          isRequired: false,
        },
        existingPaymentMethodRequired: false,
        isEmailRequired: true,
      });

      if (error) {
        Alert.alert(error.code, error.message);
        return;
      }
      console.log('this is logged :)');
      setInitialized(true);
    }
    initialize();
  }, [initGooglePay]);
```

and it seems to be working for me on first load. Could you provide a link to a minimal project that reproduces the issue you're running into?

**Comment by charliecruzan-stripe** [comment] 2022-03-04 20:54
Closing for now since this seems to be working on the most recent version. if you're still running into this issue, please let me know and share a link to a project I can use to reproduce the same behavior

**Closed by charliecruzan-stripe** 2022-03-04 20:54 UTC
Labels: invalid, reproduce
