### ISSUE TITLE
[iOS] Nothing happens after inputting a 3D secure verification code

### ISSUE THREAD

**Issue by lucasroca** [stripe/stripe-react-native#755] opened 2021-12-23 12:25 UTC
**Describe the bug**
Nothing happens after submitting a verification code

**To Reproduce**
1. Input a card that triggers a 3D secure authentication
2. A 3D secure verification modal opens
3. Input the verification code received by SMS and click "Bekræft (confirm)"
4. A loading spinner is briefly displayed, then it goes back to the initial state. See the screenshot below.

**Expected behavior**
3D secure authentication to succeed or fail

**Screenshots**
![image](https://user-images.githubusercontent.com/29613530/147240331-f0370cac-e4e9-4d57-973f-102826489ead.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 15.0

**Comment by charliecruzan-stripe** [comment] 2022-02-08 21:32
Hi, please provide a code sample or link a GitHub repo we can use to reproduce this behavior

**Comment by charliecruzan-stripe** [comment] 2022-03-15 18:43
Closing this since there's no reproducible demo- however, if you're having trouble with 3ds verification and would like to opt into our testing program, please email [3ds2-mobile-fallback@stripe.com](mailto:3ds2-mobile-fallback@stripe.com) with your [account ID](https://stripe.com/docs/dashboard#find-account-id). Thanks!

**Comment by arneson** [comment] 2022-03-21 20:46
Hi! We're having the exakt same issue and it seems to be card specific (we only experience it for some cards) and we do have an example of a card which consistently has this issue. Could this please be reopened?

**Comment by charliecruzan-stripe** [comment] 2022-03-21 20:48
Sure, is it a test card you can share?

**Comment by arneson** [comment] 2022-03-22 09:19
The problematic card we have access to is a 'real' card belonging to a customer. I think we possibly could set something up with him. Should we continue over email? simon@pelag.io

**Comment by arneson** [comment] 2022-03-22 12:07
I actually managed to resolve this. 
The issue was that we did not supply the returnURL parameter to initPaymentSheet. 
After doing this the flow continued after entering the code in the 3DS window.

**Comment by charliecruzan-stripe** [comment] 2022-03-31 13:42
Closing since this was resolved

**Closed by charliecruzan-stripe** 2022-03-31 13:42 UTC
Labels: reproduce
