### ISSUE TITLE
Android Error : Missing annotations Stripe React Native @Input

### ISSUE THREAD

**Issue by aslamanver** [stripe/stripe-react-native#1407] opened 2023-05-31 14:24 UTC
The Android builds in the Nx project are failing due to an error related to annotations when attempting to install the `stripe/react-native` package. 

However, this issue does not arise when installing the package on a new project using the react-native CLI.

```
Task :stripe_stripe-react-native:packageDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
58 actionable tasks: 2 executed, 56 up-to-date
ERROR:/Users/esfxra/monorepo/apps/test-app/node_modules/@stripe/stripe-react-native/android/src/main/res/layout/googlepay_button_dark.xml: Resource and asset merger: /Users/esfxra/monorepo/apps/test-app/node_modules/@stripe/stripe-react-native/android/src/main/res/layout/googlepay_button_dark.xml is not annotated as @Input
java.lang.IllegalStateException: /Users/esfxra/monorepo/apps/test-app/node_modules/@stripe/stripe-react-native/android/src/main/res/layout/googlepay_button_dark.xml is not annotated as @Input
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':stripe_stripe-react-native:packageDebugResources'.
>! > /Users/esfxra/monorepo/apps/test-app/node_modules/@stripe/stripe-react-native/android/src/main/res/layout/googlepay_button_dark.xml: Error: is not annotated as @Input
```

- Run npm install @stripe/stripe-react-native
- Integrate the <StripeProvider>{...}</StripeProvider> component
- Run npx nx run wifi-app:run-android
- See error

**Comment by charliecruzan-stripe** [comment] 2023-06-01 00:58
Closing as a duplicate of https://github.com/stripe/stripe-react-native/issues/1078

**Closed by charliecruzan-stripe** 2023-06-01 00:58 UTC
