### ISSUE TITLE
 No callback found with cbID [ID] and callID [ID] for  StripeSdk.presentApplePay - most likely the callback was already invoked.

### ISSUE THREAD

**Issue by aaronrondina5** [stripe/stripe-react-native#818] opened 2022-02-16 22:55 UTC
**Describe the bug**
When canceling Apple Pay after clicking to pay, error from presentApplePay leads to an exception thrown that the callback has already been used. 

**To Reproduce**
1. Present Apple Pay.
2. Click pay with passcode OR pay with finger print.
3. During loading, cancel Apple Pay (either by clicking X in top right or outside of the payment sheet.

**Expected behavior**
React native should receive an error from the confirmApplePayPayment response and should be able to handle this error.

**Smartphone (please complete the following information):**
 - Device: simulator- iPhone 11, iOS 15.0 OR actual device - iPhone 12 Mini iOS 15.2.1
 - Simulator: 

**Additional context**
Error logs:
```
Invariant Violation: No callback found with cbID 7867 and callID 3933 for  StripeSdk.presentApplePay - most likely the callback was already invoked. Args: '[{"code":"Canceled","message":"Apple pay payment has been cancelled","domain":"RCTErrorDomain","userInfo":null,"nativeStackIOS":["0   RDY                                 0x00000001089d0c70 RCTJSErrorFromCodeMessageAndNSError + 112","1   RDY                                 0x000000010896121f __41-[RCTModuleMethod processMethodSignat...(truncated)...","2   RDY                                 0x00000001090cfb87 $sSo8NSStringCSgACSo7NSErrorCSgIeyByyy_SS...(truncated)...","3   RDY                                 0x00000001090d9d0c $s19stripe_react_native9StripeSdkC15apple...(truncated)...","4   RDY                                 0x00000001090da08c $s19stripe_react_native9StripeSdkC15apple...(truncated)...","5   RDY                                 0x0000000108d0cb8b $s6Stripe18STPApplePayContextC39paymentAu...(truncated)...","6   RDY                                 0x0000000108c2ef78 $sIeg_IeyB_TR + 40","7   libdispatch.dylib                   0x00007fff20110876 _dispatch_call_block_and_release + 12","8   libdispatch.dylib                   0x00007fff20111a56 _dispatch_client_callout + 8","9   libdispatch.dylib                   0x00007fff2011ee20 _dispatch_main_queue_callback_4CF + 1073","10  CoreFoundation                      0x00007fff2036985d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9","11  CoreFoundation                      0x00007fff203640ba __CFRunLoopRun + 2772","12  CoreFoundation                      0x00007fff20363103 CFRunLoopRunSpecific + 567","13  GraphicsServices                    0x00007fff2c851cd3 GSEventRunModal + 139","14  UIKitCore                           0x00007fff24ffbe63 -[UIApplication _run] + 928","15  UIKitCore                           0x00007fff25000a53 UIApplicationMain + 101","16  RDY                                 0x000000010813ed38 main + 104","17  dyld                                0x000000010c4afe1e start_sim + 10","18  ???                                 0x000000010d01c4fe 0x0 + 4513187070","19  ???                                 0x0000000000000000 0x0 + 0","20  RDY                                 0x000000010813a000 __dso_handle + 0"]}]'
```

Here is our Apple Pay function:
```
const {presentApplePay, isApplePaySupported, confirmApplePayPayment} = useApplePay()
...
function applePay() {
        if (paymentSummaryDetails.usCents.total <= 0) {
            handleCheckoutResult(false, 'Cannot Apple Pay with a $0.00 check', false)
        } else if (!isApplePaySupported) {
            handleCheckoutResult(false, 'Sorry, your device does not support Apple Pay', false)
        } else {
            const cartItems = summaryToApplePaySummaryItems(paymentSummaryDetails, cart!.merchant.name)
            const {error: presentApplePayError} = await presentApplePay({cartItems, country: 'US', currency: 'USD'})

            if (presentApplePayError) {
                if (presentApplePayError.code !== ApplePayError.Canceled) {
                    handleCheckoutResult(false, 'Apple Pay failed', false)
                }
            } else {
                try {
                    toggleShouldBlockOrder(true)
                    const {paymentIntent} = await checkout(
                        cart!.items,
                        paymentSummaryDetails!.usCents.tip,
                        false,
                        checkoutOptions.orderTiming,
                        undefined,
                        checkoutOptions.diningOption,
                        checkoutOptions.placeInSeconds
                    )
                    const {error: confirmApplePayError} = await confirmApplePayPayment(paymentIntent!!.stripeClientSecret)
                    if (confirmApplePayError) {
                        handleCheckoutResult(false, 'Apple Pay failed', true)
                    } else {
                        handleCheckoutResult(true, '', false)
                    }
                } catch (e) {
                    handleCheckoutResult(false, 'Apple Pay failed', true)
                }
            }
        }
    }
```

**Comment by charliecruzan-stripe** [comment] 2022-02-24 20:33
Hi! [I tried reproducing this according to your steps](https://user-images.githubusercontent.com/97612659/155602847-419f5888-a4f2-4f77-ab21-86fe46a1d36b.mov) & using our example app, but I'm getting the correct error message back:

What version are you using?

**Comment by aaronrondina5** [comment] 2022-03-01 17:58
0.1.2

**Comment by aaronrondina5** [comment] 2022-03-09 19:24
Updated to 0.3.0

- the exception no longer occurs.
- However, if you click outside the palette after confirmation (as in the case above), `confirmApplePayPayment` never resolves. 
- Do we just have to write our own time out functionality for this edge case?

**Comment by charliecruzan-stripe** [comment] 2022-03-09 19:43
`confirmApplePayPayment` is resolving for me on v0.3.0 in this case with the `Canceled` error code. Can you try running the code from the [example ApplePay screen?](https://github.com/stripe/stripe-react-native/blob/master/example/src/screens/ApplePayScreen.tsx)

**Comment by charliecruzan-stripe** [comment] 2022-03-23 13:04
It's a generic error, so I'm not sure it's related. Going to close this since haven't received an answer regarding the above. If you run into this issue, please create a reproducible demo that narrows the issue down to a recent version of `@stripe/stripe-react-native`

**Closed by charliecruzan-stripe** 2022-03-23 13:04 UTC
Labels: ios, reproduce

**Comment by yousefamar** [comment] 2023-01-05 12:19
Just a note for future Googlers since this is the main result -- I'm using Expo, and solved this by:

- upgrading to the latest Expo version
- upgrading to the latest stripe-react-native version (ignore the complaints of `expo doctor`, everything seems to work even with mismatching dependencies)
- If you're using `initStripe`, change to the `StripeProvider` setup. I don't know why this made a difference, but it did.
