### ISSUE TITLE
Add Credit Card From Not working on Android but working on iOS (Android fires focusField event when attempting to submit form)

### ISSUE THREAD

**Issue by jheslop25** [stripe/stripe-react-native#729] opened 2021-11-19 22:37 UTC
**Describe the bug**

We have a react native project that allows our customers to order from various local restaurants and food trucks. We are having problems with adding payment methods on android. iOS is working just fine under exactly the same circumstances.

We are using the standard SDK CardForm element to capture the user's card info. 

On iOS, when we press the "save payment" button in our app, it works as expected and saves the payment. 

On Android, with a correctly entered test card, the CardForm element seems to be overriding our save button and firing a focusField event that targets the cursor to the card number field as if it were incorrectly entered. But it doesn't show any errors as it would if the data was invalid. The CardForm is also blocking the "close button" which has nothing to do with the card form and simply flips a boolean to hide the form, instead it fires the same "focusField" event. Obviously, this is a serious problem that's blocking us from going to production. 

Can anyone lend any insight on why this could be happening? I realize that it can be hard to exactly diagnose these sorts of issues, but any thoughts or suggestions would be helpful. 

Also, for the record, this was working correctly on both platforms as of 2 months ago when we finished initial development and testing. Its only failing now right before we need to go to production with our first few clients. Because of course something always goes wrong at the 11th hour :) 

Thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charliecruzan-stripe** [comment] 2022-02-11 22:05
hi @jheslop25 , it's odd that it was working and then stopped working- did a new version of `@stripe/stripe-react-native` cause the break, or was it changes internal to your codebase? 

Also, please fill in the rest of the issue template- especially the steps to reproduce the issue, otherwise it's difficult to guess at what the issue might be

**Comment by charliecruzan-stripe** [comment] 2022-03-04 20:56
Closing since there's no reproduction shared in the issue template, so it's hard to say what could cause the issues you're seeing. If you can share a reproducible demo, I'm happy to take a look!

**Closed by charliecruzan-stripe** 2022-03-04 20:56 UTC
Labels: android, reproduce
